//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class accessorydetail
    {
        public int stp_number { get; set; }
        public string cmp_id { get; set; }
        public string acc_id { get; set; }
        public System.DateTime acd_date { get; set; }
        public int acd_in { get; set; }
        public int acd_out { get; set; }
        public Nullable<decimal> acd_cost { get; set; }
        public Nullable<decimal> acd_total { get; set; }
        public string acd_code { get; set; }
        public string mpp_id { get; set; }
        public string trl_number { get; set; }
        public string acd_processed { get; set; }
        public string acd_type { get; set; }
        public byte[] timestamp { get; set; }
    }
}
