//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class acct_glnum
    {
        public string tts_co { get; set; }
        public string acct_type { get; set; }
        public int sequence_id { get; set; }
        public string gl_key1 { get; set; }
        public string gl_key2 { get; set; }
        public string gl_key3 { get; set; }
        public string gl_key4 { get; set; }
        public string gl_key5 { get; set; }
        public string gl_key6 { get; set; }
        public string gl_key7 { get; set; }
        public string gl_key8 { get; set; }
        public string gl_key9 { get; set; }
        public string gl_key10 { get; set; }
        public string seg1 { get; set; }
        public string seg2 { get; set; }
        public string seg3 { get; set; }
        public string seg4 { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
