//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_payment_header
    {
        public int pad_batch { get; set; }
        public Nullable<System.DateTime> pad_date { get; set; }
        public string pad_filename { get; set; }
        public Nullable<int> pad_recordcount { get; set; }
        public Nullable<int> pad_successcount { get; set; }
        public Nullable<int> pad_failurecount { get; set; }
        public string pad_ap_voucher_nbr { get; set; }
    }
}
