//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class apsummary
    {
        public int stlmnt { get; set; }
        public string type { get; set; }
        public string id { get; set; }
        public string payto { get; set; }
        public string docno { get; set; }
        public System.DateTime period { get; set; }
        public string status { get; set; }
        public decimal netamt { get; set; }
        public decimal remaining { get; set; }
        public Nullable<decimal> gpcurtrxam { get; set; }
    }
}
