//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class assetassignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assetassignment()
        {
            this.assetassignment_tour_dtl = new HashSet<assetassignment_tour_dtl>();
        }
    
        public Nullable<int> lgh_number { get; set; }
        public int asgn_number { get; set; }
        public string asgn_type { get; set; }
        public string asgn_id { get; set; }
        public Nullable<System.DateTime> asgn_date { get; set; }
        public Nullable<int> asgn_eventnumber { get; set; }
        public string asgn_controlling { get; set; }
        public string asgn_status { get; set; }
        public Nullable<System.DateTime> asgn_dispdate { get; set; }
        public Nullable<System.DateTime> asgn_enddate { get; set; }
        public string asgn_dispmethod { get; set; }
        public Nullable<int> mov_number { get; set; }
        public byte[] timestamp { get; set; }
        public string pyd_status { get; set; }
        public string actg_type { get; set; }
        public Nullable<int> evt_number { get; set; }
        public Nullable<int> asgn_trl_first_asgn { get; set; }
        public Nullable<int> asgn_trl_last_asgn { get; set; }
        public Nullable<int> last_evt_number { get; set; }
        public Nullable<int> last_dne_evt_number { get; set; }
        public Nullable<int> next_opn_evt_number { get; set; }
        public string aa_nonprimary_asset { get; set; }
        public string asgn_branch { get; set; }
        public string termCode { get; set; }
        public Nullable<System.DateTime> asgn_pay_usedate { get; set; }
        public string asgn_pay_usedate_setting { get; set; }
        public string fgt_number { get; set; }
        public string asgn_payto { get; set; }
        public Nullable<int> PayScheduleId { get; set; }
        public Nullable<int> asgn_pld_event { get; set; }
        public Nullable<int> fgt_asset_order_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assetassignment_tour_dtl> assetassignment_tour_dtl { get; set; }
    }
}
