//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class associate_fee_schedule_inv_map
    {
        public string brn_id { get; set; }
        public string fee_schedule_itemcode { get; set; }
        public string cht_itemcode { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
    }
}
