//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billto_Control_COPY
    {
        public string fgt_shipper { get; set; }
        public string fgt_consignee { get; set; }
        public string fgt_terms { get; set; }
        public string fgt_billto { get; set; }
        public string masterord_number { get; set; }
        public int Id { get; set; }
    }
}
