//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDoctype
    {
        public string cmp_id { get; set; }
        public string bdt_doctype { get; set; }
        public byte bdt_sequence { get; set; }
        public string bdt_inv_required { get; set; }
        public string bdt_inv_attach { get; set; }
        public string bdt_required_for_application { get; set; }
        public string bdt_required_for_fgt_event { get; set; }
        public string bdt_inv_attachBC { get; set; }
        public string bdt_inv_attachMisc { get; set; }
        public string bdt_required_for_dispatch { get; set; }
        public int BillDocTypes_ident { get; set; }
        public string bdt_inv_attachcredit { get; set; }
        public string bdt_inv_attachrebill { get; set; }
        public string bdt_inv_attachsupp { get; set; }
    }
}
