//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class can_Contact
    {
        public string con_id { get; set; }
        public string car_carrierid { get; set; }
        public string con_firstname { get; set; }
        public string con_lastname { get; set; }
        public string con_phone { get; set; }
        public string con_fax { get; set; }
        public string con_address1 { get; set; }
        public string con_address2 { get; set; }
        public string con_city { get; set; }
        public string con_state { get; set; }
        public string con_zip { get; set; }
    }
}
