//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class can_Loads
    {
        public int ld_transactionnum { get; set; }
        public string car_carrierid { get; set; }
        public string all_allianceid { get; set; }
        public string con_contactid { get; set; }
        public string ld_contact { get; set; }
        public Nullable<System.DateTime> ld_postdate { get; set; }
        public Nullable<System.DateTime> ld_expiredate { get; set; }
        public Nullable<System.DateTime> ld_shipdate { get; set; }
        public Nullable<System.DateTime> ld_deliverydate { get; set; }
        public string ld_origincity { get; set; }
        public string ld_originstate { get; set; }
        public string ld_originname { get; set; }
        public string ld_destcity { get; set; }
        public string ld_deststate { get; set; }
        public string ld_destname { get; set; }
        public string ld_comments { get; set; }
        public string ld_equipmenttype { get; set; }
        public string ld_product { get; set; }
        public Nullable<decimal> ld_weight { get; set; }
        public string ld_weightunit { get; set; }
        public Nullable<decimal> ld_volumn { get; set; }
        public string ld_volumnunit { get; set; }
        public Nullable<int> ld_count { get; set; }
        public string ld_countunit { get; set; }
        public Nullable<decimal> ld_linehaulcharges { get; set; }
        public string ld_currency { get; set; }
        public string ld_status { get; set; }
        public string ld_acceptedby { get; set; }
        public Nullable<int> ld_feet { get; set; }
        public string ld_ordernumber { get; set; }
        public string ld_referencetype { get; set; }
        public string ld_referencenumber { get; set; }
        public string ld_restrictto1 { get; set; }
        public string ld_restrictto2 { get; set; }
        public string ld_restrictto3 { get; set; }
        public string ld_restrictto4 { get; set; }
        public Nullable<int> ord_hdrnumber { get; set; }
        public string ord_number { get; set; }
        public Nullable<System.DateTime> ld_awarded_dt { get; set; }
        public string ld_nlm_critical { get; set; }
        public string ld_network { get; set; }
        public Nullable<int> nlm_shipment_number { get; set; }
        public Nullable<int> nlm_accid { get; set; }
        public Nullable<int> ld_miles { get; set; }
        public Nullable<int> mov_number { get; set; }
        public Nullable<int> lgh_number { get; set; }
        public string ld_origzip { get; set; }
        public string ld_destzip { get; set; }
        public Nullable<int> all_alliancesn { get; set; }
        public string nlm_required_vehicle { get; set; }
        public string nlm_acc_name { get; set; }
        public string nlm_first_right_refusal { get; set; }
    }
}
