//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrierLTLServiceZone
    {
        public string car_id { get; set; }
        public string Zip { get; set; }
        public string ServiceZone { get; set; }
        public string OriginServiceLevel { get; set; }
        public int OriginExtraDays { get; set; }
        public string DestinationServiceLevel { get; set; }
        public int DestinationExtraDays { get; set; }
    }
}
