//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrierCsaDocument
    {
        public int id { get; set; }
        public int docid { get; set; }
        public string doctype { get; set; }
        public string provider { get; set; }
        public string car_id { get; set; }
        public string external_id { get; set; }
        public Nullable<System.DateTime> lastupdatedate { get; set; }
        public string lastupdateuser { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string createdby { get; set; }
    }
}
