//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrierfilterlist
    {
        public int cfl_id { get; set; }
        public string cfl_userid { get; set; }
        public string cfl_abbr { get; set; }
        public string cfl_labeldef { get; set; }
        public string cfl_default { get; set; }
        public string caf_viewid { get; set; }
        public string cfl_operator { get; set; }
        public Nullable<byte> cfl_qty { get; set; }
    }
}
