//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrier411_batch_update_status
    {
        public int cab_batch_number { get; set; }
        public string cbu_update_type { get; set; }
        public Nullable<System.DateTime> cbu_batch_date { get; set; }
        public string cbu_userid { get; set; }
        public Nullable<int> cbu_batchcount { get; set; }
        public string cbu_batch_status { get; set; }
    }
}
