//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrierinsurance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public carrierinsurance()
        {
            this.carrierinsurancelimits = new HashSet<carrierinsurancelimit>();
        }
    
        public int cai_id { get; set; }
        public string car_id { get; set; }
        public string cai_insurance_type { get; set; }
        public Nullable<System.DateTime> cai_effective_dt { get; set; }
        public Nullable<System.DateTime> cai_expiration_dt { get; set; }
        public Nullable<decimal> cai_liability_limit { get; set; }
        public string cai_comment { get; set; }
        public string cai_cmpissued { get; set; }
        public string cai_updatedby { get; set; }
        public Nullable<System.DateTime> cai_updatedt { get; set; }
        public string cai_policynumber { get; set; }
        public string cai_imageURL { get; set; }
        public string cai_Source { get; set; }
        public Nullable<int> caix_id { get; set; }
        public string ciax_determination { get; set; }
        public string cai_AgentName { get; set; }
        public string cai_AgentPhone { get; set; }
        public string cai_AgentFax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrierinsurancelimit> carrierinsurancelimits { get; set; }
    }
}
