//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrier411_sms
    {
        public int sn { get; set; }
        public string sms_cas_docket_number { get; set; }
        public Nullable<int> sms_insp_total { get; set; }
        public Nullable<int> sms_driver_insp_total { get; set; }
        public Nullable<int> sms_driver_oos_insp_total { get; set; }
        public Nullable<int> sms_vehicle_insp_total { get; set; }
        public Nullable<int> sms_vehicle_oos_insp_total { get; set; }
        public Nullable<System.DateTime> sms_fit_last { get; set; }
        public string sms_safe_fit { get; set; }
        public Nullable<System.DateTime> sms_basic_last { get; set; }
        public string sms_ins_other_violation { get; set; }
        public string sms_ins_other_indicator { get; set; }
        public Nullable<decimal> sms_unsafe_prcnt { get; set; }
        public string sms_unsafe_alert { get; set; }
        public string sms_unsafe_violation { get; set; }
        public string sms_unsafe_indicator { get; set; }
        public Nullable<int> sms_unsafe_inspect { get; set; }
        public Nullable<decimal> sms_unsafe_score { get; set; }
        public Nullable<decimal> sms_fatig_prcnt { get; set; }
        public string sms_fatig_alert { get; set; }
        public string sms_fatig_violation { get; set; }
        public string sms_fatig_indicator { get; set; }
        public Nullable<int> sms_fatig_inspect { get; set; }
        public Nullable<decimal> sms_fatig_score { get; set; }
        public Nullable<decimal> sms_fit_prcnt { get; set; }
        public string sms_fit_alert { get; set; }
        public string sms_fit_violation { get; set; }
        public string sms_fit_indicator { get; set; }
        public Nullable<int> sms_fit_inspect { get; set; }
        public Nullable<decimal> sms_fit_score { get; set; }
        public Nullable<decimal> sms_cntrl_prcnt { get; set; }
        public string sms_cntrl_alert { get; set; }
        public string sms_cntrl_violation { get; set; }
        public string sms_cntrl_indicator { get; set; }
        public Nullable<int> sms_cntrl_inspect { get; set; }
        public Nullable<decimal> sms_cntrl_score { get; set; }
        public Nullable<decimal> sms_veh_prcnt { get; set; }
        public string sms_veh_alert { get; set; }
        public string sms_veh_violation { get; set; }
        public string sms_veh_indicator { get; set; }
        public Nullable<int> sms_veh_inspect { get; set; }
        public Nullable<decimal> sms_veh_score { get; set; }
        public Nullable<decimal> sms_cargo_prcnt { get; set; }
        public string sms_cargo_alert { get; set; }
        public string sms_cargo_violation { get; set; }
        public string sms_cargo_indicator { get; set; }
        public Nullable<int> sms_cargo_inspect { get; set; }
        public Nullable<decimal> sms_cargo_score { get; set; }
    }
}
