//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrierequipment
    {
        public int ceq_id { get; set; }
        public string car_id { get; set; }
        public string ceq_equipment_type { get; set; }
        public Nullable<int> ceq_units { get; set; }
    }
}
