//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrierinsurancelimit
    {
        public int cal_id { get; set; }
        public Nullable<int> cai_id { get; set; }
        public Nullable<decimal> cal_limit { get; set; }
        public string cal_description { get; set; }
        public string cal_source { get; set; }
    
        public virtual carrierinsurance carrierinsurance { get; set; }
    }
}
