//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrier411data
    {
        public int BATCH_ID { get; set; }
        public string submethod { get; set; }
        public string docket { get; set; }
        public string SAFETYRATING { get; set; }
        public Nullable<System.DateTime> SAFETYRATEDATE { get; set; }
        public Nullable<System.DateTime> SAFETYREVDATE { get; set; }
        public string SAFETYREVTYPE { get; set; }
        public string FMCSADOCKETNUMBER { get; set; }
        public string FMCSAAPPLICANTID { get; set; }
        public Nullable<int> FMCSABIPDFILED { get; set; }
        public Nullable<int> FMCSABIPDREQUIRED { get; set; }
        public string FMCSABONDFILED { get; set; }
        public string FMCSABONDREQUIRED { get; set; }
        public string FMCSABROKER { get; set; }
        public string FMCSABUSADDRESS { get; set; }
        public string FMCSABUSCITY { get; set; }
        public string FMCSABUSCOUNTRY { get; set; }
        public string FMCSABUSFAX { get; set; }
        public string FMCSABUSPHONE { get; set; }
        public string FMCSABUSSTATE { get; set; }
        public string FMCSABUSZIP { get; set; }
        public string FMCSACARGOFILED { get; set; }
        public string FMCSACARGOREQUIRED { get; set; }
        public string FMCSACOMMON { get; set; }
        public string FMCSACONTRACT { get; set; }
        public Nullable<System.DateTime> FMCSADATELASTUPDATED { get; set; }
        public string FMCSADBANAME { get; set; }
        public Nullable<decimal> FMCSADOTNUMBER { get; set; }
        public string FMCSAFREIGHT { get; set; }
        public string FMCSAHOUSEHOLD { get; set; }
        public string FMCSALEGALNAME { get; set; }
        public string FMCSAMAILADDRESS { get; set; }
        public string FMCSAMAILCITY { get; set; }
        public string FMCSAMAILCOUNTRY { get; set; }
        public string FMCSAMAILFAX { get; set; }
        public string FMCSAMAILPHONE { get; set; }
        public string FMCSAMAILSTATE { get; set; }
        public string FMCSAMAILZIP { get; set; }
        public string FMCSAPASSENGER { get; set; }
        public string FMCSAPENDINGBROKER { get; set; }
        public string FMCSAPENDINGCOMMON { get; set; }
        public string FMCSAPENDINGCONTRACT { get; set; }
        public string FMCSAREVOKINGBROKER { get; set; }
        public string FMCSAREVOKINGCOMMON { get; set; }
        public string FMCSAREVOKINGCONTRACT { get; set; }
        public Nullable<decimal> SMSINSPTOTAL { get; set; }
        public Nullable<decimal> SMSDRIVINSPTOTAL { get; set; }
        public Nullable<decimal> SMSDRIVOOSINSPTOTAL { get; set; }
        public Nullable<decimal> SMSVEHINSPTOTAL { get; set; }
        public Nullable<decimal> SMSVEHOOSINSPTOTAL { get; set; }
        public Nullable<decimal> SMSUNSAFEDRIVPCT { get; set; }
        public string SMSUNSAFEDRIVBASICALERT { get; set; }
        public string SMSUNSAFEDRIVSV { get; set; }
        public string SMSUNSAFEDRIVRDALERT { get; set; }
        public Nullable<decimal> SMSFATIGUEDRIVPCT { get; set; }
        public string SMSFATIGUEDRIVBASICALERT { get; set; }
        public string SMSFATIGUEDRIVSV { get; set; }
        public string SMSFATIGUEDRIVRDALERT { get; set; }
        public Nullable<decimal> SMSDRIVFITPCT { get; set; }
        public string SMSDRIVFITBASICALERT { get; set; }
        public string SMSDRIVFITSV { get; set; }
        public string SMSDRIVFITRDALERT { get; set; }
        public Nullable<decimal> SMSCONTRSUBSTPCT { get; set; }
        public string SMSCONTRSUBSTBASICALERT { get; set; }
        public string SMSCONTRSUBSTSV { get; set; }
        public string SMSCONTRSUBSTRDALERT { get; set; }
        public Nullable<decimal> SMSVEHMAINTPCT { get; set; }
        public string SMSVEHMAINTBASICALERT { get; set; }
        public string SMSVEHMAINTSV { get; set; }
        public string SMSVEHMAINTRDALERT { get; set; }
        public string CENSUSBEVERAGES { get; set; }
        public string CENSUSBLDGMAT { get; set; }
        public string CENSUSCARGOOTHR { get; set; }
        public string CENSUSCHEM { get; set; }
        public string CENSUSCLASS { get; set; }
        public string CENSUSCLASSDEF { get; set; }
        public string CENSUSCOALCOKE { get; set; }
        public string CENSUSCOLDFOOD { get; set; }
        public string CENSUSCONSTRUCT { get; set; }
        public string CENSUSDBNUM { get; set; }
        public string CENSUSDRIVETOW { get; set; }
        public string CENSUSDRYBULK { get; set; }
        public string CENSUSEMAILADDRESS { get; set; }
        public string CENSUSFARMSUPP { get; set; }
        public string CENSUSGARBAGE { get; set; }
        public string CENSUSGENFREIGHT { get; set; }
        public string CENSUSGRAINFEED { get; set; }
        public string CENSUSHOUSEHOLD { get; set; }
        public string CENSUSINTERMODAL { get; set; }
        public string CENSUSLIQGAS { get; set; }
        public string CENSUSLIVESTOCK { get; set; }
        public string CENSUSLOGPOLE { get; set; }
        public string CENSUSMACHLRG { get; set; }
        public Nullable<System.DateTime> CENSUSMCS150DATE { get; set; }
        public Nullable<decimal> CENSUSMCS150MILEAGEYEAR { get; set; }
        public string CENSUSMEAT { get; set; }
        public string CENSUSMETALSHEET { get; set; }
        public Nullable<decimal> CENSUSMLG150 { get; set; }
        public string CENSUSMOBILEHOME { get; set; }
        public string CENSUSMOTORVEH { get; set; }
        public string CENSUSOILFIELD { get; set; }
        public string CENSUSOTHERCARGO { get; set; }
        public string CENSUSOWNTRACT { get; set; }
        public string CENSUSOWNTRAIL { get; set; }
        public string CENSUSPAPERPROD { get; set; }
        public string CENSUSPASSENGERS { get; set; }
        public string CENSUSPRODUCE { get; set; }
        public string CENSUSTOTDRS { get; set; }
        public string CENSUSTOTPWR { get; set; }
        public string CENSUSTRMTRACT { get; set; }
        public string CENSUSTRMTRAIL { get; set; }
        public string CENSUSUSMAIL { get; set; }
        public string CENSUSUTILITY { get; set; }
        public string CENSUSWATERWELL { get; set; }
        public Nullable<decimal> SAFESTATDRSEA { get; set; }
        public Nullable<decimal> SAFESTATSMSEA { get; set; }
        public Nullable<decimal> SAFESTATVHSEA { get; set; }
        public string sRetVal { get; set; }
    }
}
