//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carriercontract
    {
        public int cct_id { get; set; }
        public string car_id { get; set; }
        public string cct_contract_type { get; set; }
        public string cct_business_entity { get; set; }
        public Nullable<System.DateTime> cct_effective_dt { get; set; }
        public string cct_comments { get; set; }
        public string cct_retired { get; set; }
        public string cct_updatedby { get; set; }
        public Nullable<System.DateTime> cct_updatedt { get; set; }
    }
}
