//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carter_tar_charges
    {
        public Nullable<decimal> Fuel { get; set; }
        public Nullable<decimal> Stops { get; set; }
        public Nullable<decimal> Misc { get; set; }
        public Nullable<decimal> Re_Delivery { get; set; }
        public Nullable<decimal> Detention { get; set; }
        public string Quotes_Carrier { get; set; }
        public string Quotes_Number { get; set; }
        public int Quotes_Main_ID { get; set; }
        public bool Quotes_Accepted { get; set; }
        public int QuoteID { get; set; }
        public string Quotes_Contact { get; set; }
    
        public virtual Carter_TAR_Main Carter_TAR_Main { get; set; }
    }
}
