//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carter_GeneralAccidentInfo
    {
        public int GI_ID { get; set; }
        public int SRP_ID { get; set; }
        public string DrugTestingSite { get; set; }
        public string DrugTestingSiteAddress { get; set; }
        public Nullable<int> DrugTestingSiteCity { get; set; }
        public string DrugTestingSitePhone { get; set; }
        public Nullable<bool> TrailerTowed { get; set; }
        public string TrailerTowedDest { get; set; }
        public string TrailerTowedDestPhone { get; set; }
        public string TrailerTowedDestAddress { get; set; }
        public Nullable<int> TrailerTowedDestCity { get; set; }
        public string Consignee { get; set; }
        public Nullable<bool> CargoSalvaged { get; set; }
        public string CargoSalvageDestName { get; set; }
        public string CargoSalvageAddress1 { get; set; }
        public string CargoSalvageAddress2 { get; set; }
        public Nullable<int> CargoSalvageCity { get; set; }
        public string CargoSalvageDestPhone { get; set; }
        public Nullable<bool> DriverLogUpToDate { get; set; }
        public string InsuranceFileNum { get; set; }
        public string InsuranceIncidentReportedTo { get; set; }
        public string InsuranceAdjuster { get; set; }
        public string InsuranceAttorney { get; set; }
        public string InsuranceAttorneyAddress { get; set; }
        public Nullable<int> InsuranceAttorneyCity { get; set; }
        public string InsuranceAttorneyPhone { get; set; }
        public string ChargesFiledAgainst { get; set; }
        public string WeatherConditions { get; set; }
        public string RoadConditions { get; set; }
        public Nullable<bool> RoadDivided { get; set; }
        public Nullable<int> RoadLaneCount { get; set; }
        public string MiscNotes { get; set; }
        public string TractorDirectionofTravel { get; set; }
        public string TractorSpeedMeasurement { get; set; }
        public Nullable<int> NbrOfVehicles { get; set; }
        public Nullable<System.DateTime> TimeOfFirstCall { get; set; }
        public string DriverPhone { get; set; }
        public string DispatcherName { get; set; }
        public Nullable<System.DateTime> SafetyNotifiedTime { get; set; }
        public string SafetyPersonnelNotified { get; set; }
        public Nullable<bool> MAWNeeded { get; set; }
        public Nullable<bool> AnyVehicleTowed { get; set; }
        public Nullable<byte> Submitted { get; set; }
        public Nullable<System.DateTime> FormStarted { get; set; }
    }
}
