//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carter_AccidentPassenger
    {
        public int PS_ID { get; set; }
        public int SRP_ID { get; set; }
        public Nullable<int> OVD_ID { get; set; }
        public Nullable<int> INJ_ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> City { get; set; }
        public string PhoneNum { get; set; }
        public string Role { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    }
}
