//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carter_Claims
    {
        public int Claim_ID { get; set; }
        public Nullable<decimal> Claim_Cost { get; set; }
        public bool Claim_isPaid { get; set; }
        public Nullable<decimal> Claim_AmtRecovered { get; set; }
        public bool Claim_isDenied { get; set; }
        public string Claim_CAR { get; set; }
        public int Claim_OSDID { get; set; }
        public System.DateTime Claim_DateOpen { get; set; }
        public Nullable<System.DateTime> Claim_DateClosed { get; set; }
        public string Claim_OpenedBy { get; set; }
        public string Claim_ClosedBy { get; set; }
    
        public virtual carter_osd_main carter_osd_main { get; set; }
    }
}
