//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carter_NonDriverEmployees
    {
        public string EMPLOYID { get; set; }
        public string LASTNAME { get; set; }
        public string FRSTNAME { get; set; }
        public string MIDLNAME { get; set; }
        public string EMPLCLAS { get; set; }
        public string DB { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public string COUNTY { get; set; }
        public string COUNTRY { get; set; }
        public string TESTSEL { get; set; }
        public string SSN { get; set; }
    }
}
