//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carter_RANUpdate1
    {
        public int InvHdrNumber { get; set; }
        public int OrdHdrNumber { get; set; }
        public int BOLID { get; set; }
        public int FgtNumber { get; set; }
        public string RefType { get; set; }
        public string RefNum { get; set; }
        public string BOLStage { get; set; }
    }
}
