//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carter_modules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public carter_modules()
        {
            this.Carter_AccessAssgn = new HashSet<Carter_AccessAssgn>();
        }
    
        public int Mod_AppID { get; set; }
        public int Mod_ID { get; set; }
        public string Mod_Name { get; set; }
        public bool Mod_DefaultPerm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carter_AccessAssgn> Carter_AccessAssgn { get; set; }
        public virtual carter_applications carter_applications { get; set; }
    }
}
