//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carter_DriverViolation
    {
        public string mpp_id { get; set; }
        public string mpp_domicile { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateToRemove { get; set; }
        public string UserName { get; set; }
    }
}
