//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdfuelbill_header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cdfuelbill_header()
        {
            this.fuelimport_ftpinfo = new HashSet<fuelimport_ftpinfo>();
            this.cdfuelbill_layout = new HashSet<cdfuelbill_layout>();
            this.cdfuelbill_mappings_tbl = new HashSet<cdfuelbill_mappings_tbl>();
            this.cdfuelproducts = new HashSet<cdfuelproduct>();
        }
    
        public int cfb_xfacetype { get; set; }
        public string cfb_xfacename { get; set; }
        public string cfb_xfacedescription { get; set; }
        public int cfb_systemcode { get; set; }
        public int cfb_retired { get; set; }
        public string cfb_currency { get; set; }
        public string cfb_accountid { get; set; }
        public string cfb_customerid { get; set; }
        public string cfb_shortname { get; set; }
        public string cfb_payto { get; set; }
        public string cfb_gp_payableaccount { get; set; }
        public int cfb_bulk { get; set; }
        public Nullable<int> cfb_GMTDelta { get; set; }
        public string cfb_license_key { get; set; }
        public string cfb_license_key2 { get; set; }
        public string cfb_preprocess { get; set; }
        public string cfb_validate_otherfuel_code { get; set; }
        public string cfb_process_other_fuel { get; set; }
        public string cfb_vendor { get; set; }
        public string cfb_cardstatusdef { get; set; }
        public string cfb_DisableAutoCreateCard { get; set; }
        public string cfb_rebateprogram { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fuelimport_ftpinfo> fuelimport_ftpinfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdfuelbill_layout> cdfuelbill_layout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdfuelbill_mappings_tbl> cdfuelbill_mappings_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cdfuelproduct> cdfuelproducts { get; set; }
    }
}
