//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdfuelbill_gppayable
    {
        public System.DateTime cfbgp_transdate { get; set; }
        public string cfbgp_transnumber { get; set; }
        public string cfbgp_accountid { get; set; }
        public string cfbgp_unitnumber { get; set; }
        public string cfbgp_truckstopinvoicenumber { get; set; }
        public Nullable<decimal> cfbgp_totaldue { get; set; }
        public string cfbgp_tripnumber { get; set; }
        public string cfbgp_employeenum { get; set; }
        public string cfbgp_truckstopcode { get; set; }
        public string cfbgp_truckstopname { get; set; }
        public string cfbgp_referencenumber { get; set; }
        public string cfbgp_payto { get; set; }
        public string cfbgp_gl_number { get; set; }
        public string cfbgp_transferred_togp { get; set; }
        public string cfbgp_directbill { get; set; }
        public Nullable<decimal> cfbgp_feefueloilproducts { get; set; }
        public Nullable<decimal> cfbgp_advancecharge { get; set; }
    }
}
