//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdfuelbill
    {
        public string cfb_accountid { get; set; }
        public string cfb_customerid { get; set; }
        public System.DateTime cfb_transdate { get; set; }
        public string cfb_transnumber { get; set; }
        public string cfb_cardnumber { get; set; }
        public string cfb_employeenum { get; set; }
        public string cfb_unitnumber { get; set; }
        public Nullable<int> cfb_trchubmiles { get; set; }
        public string cfb_trailernumber { get; set; }
        public string cfb_tripnumber { get; set; }
        public Nullable<decimal> cfb_totaldue { get; set; }
        public Nullable<decimal> cfb_feefueloilproducts { get; set; }
        public Nullable<decimal> cfb_trcgallons { get; set; }
        public Nullable<decimal> cfb_trccostpergallon { get; set; }
        public Nullable<decimal> cfb_trccost { get; set; }
        public Nullable<decimal> cfb_reefergallons { get; set; }
        public Nullable<decimal> cfb_reefercostpergallon { get; set; }
        public Nullable<decimal> cfb_reefercost { get; set; }
        public Nullable<int> cfb_oilquarts { get; set; }
        public Nullable<decimal> cfb_oilcost { get; set; }
        public Nullable<decimal> cfb_advanceamt { get; set; }
        public Nullable<decimal> cfb_advancecharge { get; set; }
        public string cfb_productcode1 { get; set; }
        public Nullable<decimal> cfb_productamt1 { get; set; }
        public string cfb_productcode2 { get; set; }
        public Nullable<decimal> cfb_productamt2 { get; set; }
        public string cfb_productcode3 { get; set; }
        public Nullable<decimal> cfb_productamt3 { get; set; }
        public string cfb_productcode4 { get; set; }
        public Nullable<decimal> cfb_productamount4 { get; set; }
        public Nullable<decimal> cfb_tax1 { get; set; }
        public Nullable<decimal> cfb_tax2 { get; set; }
        public Nullable<decimal> cfb_tax3 { get; set; }
        public Nullable<decimal> cfb_tax4 { get; set; }
        public Nullable<decimal> cfb_rebateamount { get; set; }
        public Nullable<decimal> cfb_rebateamt { get; set; }
        public string cfb_truckstopinvoicenumber { get; set; }
        public string cfb_truckstopcode { get; set; }
        public string cfb_truckstopname { get; set; }
        public string cfb_truckstopcityname { get; set; }
        public string cfb_truckstopstate { get; set; }
        public string cfb_focusorselect { get; set; }
        public string cfb_network_ts { get; set; }
        public string cfb_directbill { get; set; }
        public string cfb_currencytype { get; set; }
        public string cfb_currency { get; set; }
        public string cfb_nonbillableitem { get; set; }
        public string cfb_gp_payto { get; set; }
        public string cfb_gp_payto_indicator { get; set; }
        public string cfb_gp_company { get; set; }
        public string cfb_gp_glnumber { get; set; }
        public string cfb_gp_suspense_glnumber { get; set; }
        public string cfb_plusless { get; set; }
        public string cfb_referencenumber { get; set; }
        public string cfb_checknumber { get; set; }
        public string cfb_transferred_to_gp { get; set; }
        public string cfb_error { get; set; }
        public string cfb_updatedby { get; set; }
        public Nullable<System.DateTime> cfb_updateddate { get; set; }
        public string cfb_export_to_tmt { get; set; }
        public string cfb_reeferfuelcode { get; set; }
        public string cfb_tractorfuelcode { get; set; }
        public string cfb_dieselnbr1fuelcode { get; set; }
        public string cfb_otherfuelcode { get; set; }
        public Nullable<decimal> cfb_otherfuelcost { get; set; }
        public Nullable<decimal> cfb_dieselnbr1fuelcost { get; set; }
        public Nullable<decimal> cfb_dieselnbr1gallons { get; set; }
        public Nullable<decimal> cfb_dieselnbr1costpergallon { get; set; }
        public Nullable<decimal> cfb_otherfuelgallons { get; set; }
        public Nullable<decimal> cfb_otherfuelcostpergallon { get; set; }
        public Nullable<decimal> cfb_advanceamt2 { get; set; }
        public Nullable<int> cfb_prevhubmiles { get; set; }
        public string cfb_fuelbillingflag { get; set; }
        public string cfb_cashbillingflag { get; set; }
        public string cfb_product1billingflag { get; set; }
        public string cfb_product2billingflag { get; set; }
        public string cfb_product3billingflag { get; set; }
        public string cfb_ServiceCenterChain { get; set; }
        public Nullable<int> cfb_xfacetype { get; set; }
        public string cfb_shortname { get; set; }
        public string cfb_processed { get; set; }
        public string cfb_fuelprocessed { get; set; }
        public string cfb_payprocessed { get; set; }
        public string cfb_oilbillingflag { get; set; }
        public string cfb_reeferbillingflag { get; set; }
        public string cfb_fuel_processed { get; set; }
        public string cfb_pay_processed { get; set; }
        public string cfb_authnumber { get; set; }
        public Nullable<decimal> cfb_reefauthgallons { get; set; }
        public Nullable<decimal> cfb_reefauthcostpergallon { get; set; }
        public Nullable<decimal> cfb_reefauthcost { get; set; }
        public string cfb_reefauthfuelcode { get; set; }
        public string cfb_reefauthaction { get; set; }
        public Nullable<decimal> cfb_tax5 { get; set; }
        public Nullable<decimal> cfb_tax6 { get; set; }
        public Nullable<int> ord_hdrnumber { get; set; }
        public Nullable<int> lgh_number { get; set; }
        public string ord_number { get; set; }
        public string trc_owner { get; set; }
        public string cfb_otherfuelprocessed { get; set; }
        public string cfb_add_props { get; set; }
        public Nullable<int> cfb_policy_number { get; set; }
        public string cfb_approcessed { get; set; }
        public string cfb_cancel { get; set; }
        public string cfb_advancecode { get; set; }
        public string cfb_rfid_trans { get; set; }
        public string cfb_manualreeferauth { get; set; }
        public string cfb_tax1code { get; set; }
        public string cfb_tax2code { get; set; }
        public string cfb_tax3code { get; set; }
        public string cfb_tax4code { get; set; }
        public string cfb_drv_pin { get; set; }
    
        public virtual cashcard cashcard { get; set; }
        public virtual cdacctcode cdacctcode { get; set; }
        public virtual cdcustcode cdcustcode { get; set; }
        public virtual truckstop truckstop { get; set; }
    }
}
