//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cdsecuritycard
    {
        public string csc_cardnumber { get; set; }
        public string cac_id { get; set; }
        public string csc_generic { get; set; }
        public string csc_userid { get; set; }
        public string csc_ecb { get; set; }
        public string csc_codeword { get; set; }
        public string csc_vendor { get; set; }
        public string ccc_id { get; set; }
        public string csc_vendor_userid { get; set; }
        public int csc_id { get; set; }
        public Nullable<decimal> csc_advancemax { get; set; }
        public string csc_asgntype { get; set; }
        public string csc_secondary_codeword { get; set; }
        public string csc_secondary_vendor_userid { get; set; }
    
        public virtual cdacctcode cdacctcode { get; set; }
    }
}
