//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkcall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public checkcall()
        {
            this.MobileCommMessageLinkCheckCalls = new HashSet<MobileCommMessageLinkCheckCall>();
        }
    
        public int ckc_number { get; set; }
        public string ckc_status { get; set; }
        public string ckc_asgntype { get; set; }
        public string ckc_asgnid { get; set; }
        public System.DateTime ckc_date { get; set; }
        public string ckc_event { get; set; }
        public Nullable<int> ckc_city { get; set; }
        public string ckc_comment { get; set; }
        public string ckc_updatedby { get; set; }
        public System.DateTime ckc_updatedon { get; set; }
        public Nullable<int> ckc_latseconds { get; set; }
        public Nullable<int> ckc_longseconds { get; set; }
        public Nullable<int> ckc_lghnumber { get; set; }
        public string ckc_tractor { get; set; }
        public string ckc_extsensoralarm { get; set; }
        public string ckc_vehicleignition { get; set; }
        public Nullable<double> ckc_milesfrom { get; set; }
        public string ckc_directionfrom { get; set; }
        public string ckc_validity { get; set; }
        public string ckc_mtavailable { get; set; }
        public Nullable<int> ckc_minutes { get; set; }
        public Nullable<int> ckc_mileage { get; set; }
        public string ckc_home { get; set; }
        public string ckc_cityname { get; set; }
        public string ckc_state { get; set; }
        public string ckc_zip { get; set; }
        public string ckc_commentlarge { get; set; }
        public Nullable<int> ckc_minutes_to_final { get; set; }
        public Nullable<int> ckc_miles_to_final { get; set; }
        public Nullable<int> ckc_Odometer { get; set; }
        public Nullable<int> TripStatus { get; set; }
        public Nullable<int> ckc_odometer2 { get; set; }
        public Nullable<int> ckc_speed { get; set; }
        public Nullable<int> ckc_speed2 { get; set; }
        public Nullable<double> ckc_heading { get; set; }
        public Nullable<int> ckc_gps_type { get; set; }
        public Nullable<double> ckc_gps_miles { get; set; }
        public Nullable<double> ckc_fuel_meter { get; set; }
        public Nullable<int> ckc_idle_meter { get; set; }
        public string ckc_ExtraData01 { get; set; }
        public string ckc_ExtraData02 { get; set; }
        public string ckc_ExtraData03 { get; set; }
        public string ckc_ExtraData04 { get; set; }
        public string ckc_ExtraData05 { get; set; }
        public string ckc_ExtraData06 { get; set; }
        public string ckc_ExtraData07 { get; set; }
        public string ckc_ExtraData08 { get; set; }
        public string ckc_ExtraData09 { get; set; }
        public string ckc_ExtraData10 { get; set; }
        public string ckc_ExtraData11 { get; set; }
        public string ckc_ExtraData12 { get; set; }
        public string ckc_ExtraData13 { get; set; }
        public string ckc_ExtraData14 { get; set; }
        public string ckc_ExtraData15 { get; set; }
        public string ckc_ExtraData16 { get; set; }
        public string ckc_ExtraData17 { get; set; }
        public string ckc_ExtraData18 { get; set; }
        public string ckc_ExtraData19 { get; set; }
        public string ckc_ExtraData20 { get; set; }
        public Nullable<int> ckc_AssociatedMsgSN { get; set; }
        public string ckc_TimeZone { get; set; }
        public string ckc_mcommsystem { get; set; }
        public string ckc_mcommcity { get; set; }
        public string ckc_mcommcitystate { get; set; }
        public Nullable<int> ckc_mcommsplc { get; set; }
        public string ckc_mcommfence { get; set; }
        public string ckc_mcommfenceevent { get; set; }
        public string ckc_QCTTEvent { get; set; }
        public string ckc_subsistence_qualified { get; set; }
        public Nullable<short> ckc_miles_to_next { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileCommMessageLinkCheckCall> MobileCommMessageLinkCheckCalls { get; set; }
    }
}
