//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmpemailmsg
    {
        public string cmp_id { get; set; }
        public string mail_type { get; set; }
        public Nullable<System.DateTime> updateddate { get; set; }
        public Nullable<int> ord_hdrnumber { get; set; }
        public Nullable<int> mov_number { get; set; }
        public Nullable<int> stp_number { get; set; }
        public string events { get; set; }
        public string ord_number { get; set; }
        public string email_address { get; set; }
        public string contact_name { get; set; }
        public string type { get; set; }
        public string msgtype { get; set; }
        public string message { get; set; }
        public string cmp_name { get; set; }
        public string stp_type { get; set; }
        public string firstlastflags { get; set; }
        public string trailertractor { get; set; }
    }
}
