//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmpOrdReqAddtlProReq
    {
        public int corapr_id { get; set; }
        public int prq_id { get; set; }
        public Nullable<int> corapr_seq { get; set; }
        public string revtype1 { get; set; }
        public string revtype2 { get; set; }
        public string revtype3 { get; set; }
        public string revtype4 { get; set; }
        public string last_updateby { get; set; }
        public Nullable<System.DateTime> last_updatedate { get; set; }
    }
}
