//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class commodity_prior_rules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public commodity_prior_rules()
        {
            this.commodity_invalid_subcodes = new HashSet<commodity_invalid_subcodes>();
            this.commodity_prior_subcodes = new HashSet<commodity_prior_subcodes>();
        }
    
        public int ID { get; set; }
        public string prior_cmd_class { get; set; }
        public string prior_cmd_class2 { get; set; }
        public string prior_cmd_code { get; set; }
        public string invalid_cmd_class { get; set; }
        public string invalid_cmd_class2 { get; set; }
        public string invalid_cmd_code { get; set; }
        public string IsPrevent { get; set; }
        public int LoadsBack { get; set; }
        public string cpr_cleaning { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commodity_invalid_subcodes> commodity_invalid_subcodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commodity_prior_subcodes> commodity_prior_subcodes { get; set; }
    }
}
