//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyPlannerConfigurations_SubscriptionArguments
    {
        public int cpsa_Id { get; set; }
        public int cps_Id { get; set; }
        public string cpsa_argument { get; set; }
        public string cpsa_argumentMap { get; set; }
        public int cpsa_sequence { get; set; }
        public Nullable<System.DateTime> cpsa_created { get; set; }
        public string cpsa_created_by { get; set; }
        public Nullable<System.DateTime> cpsa_updated { get; set; }
        public string cpsa_updated_by { get; set; }
    }
}
