//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_splc
    {
        public int cst_id { get; set; }
        public string cst_cmp_id { get; set; }
        public string cmp_splc { get; set; }
        public string cmp_splc_sub { get; set; }
    }
}
