//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_tankdetail
    {
        public string cmp_id { get; set; }
        public int cmp_tank_id { get; set; }
        public string cmd_code { get; set; }
        public int TankSize { get; set; }
        public int Ullage { get; set; }
        public int ShutDownGallons { get; set; }
        public decimal PMDeliveryPercentage { get; set; }
        public int DailyAverageWeeksBack { get; set; }
        public string CompanyType { get; set; }
        public string cmd_class { get; set; }
        public Nullable<int> forecast_bucket { get; set; }
        public Nullable<decimal> Diameter { get; set; }
        public string cmd_volumeunit { get; set; }
        public Nullable<int> OrderThreshold { get; set; }
        public string GenerationRule { get; set; }
        public Nullable<decimal> PercentOfForecast { get; set; }
        public Nullable<int> ForecastID { get; set; }
        public string TankTranslation { get; set; }
        public string model_id { get; set; }
        public Nullable<decimal> tank_hours_offset { get; set; }
        public Nullable<decimal> ThresholdPercentofSales { get; set; }
        public string ManifoldGroup { get; set; }
        public string IsManifolded { get; set; }
        public Nullable<int> DwellTime { get; set; }
        public string ActiveCommodityCode { get; set; }
        public string ValidCommodityList { get; set; }
        public int QuoteVolume { get; set; }
        public string IsQuotable { get; set; }
        public Nullable<double> InchesToGallonsFactor { get; set; }
        public Nullable<double> VolumeUnitWeight { get; set; }
        public string IsPumpManifold { get; set; }
        public string isproducing { get; set; }
        public Nullable<double> cmd_rvp { get; set; }
        public string TankRejected { get; set; }
        public Nullable<System.DateTime> LastRejectionDate { get; set; }
        public long ctd_identity { get; set; }
        public Nullable<decimal> Shrinkage_Incrustation_Factor { get; set; }
        public Nullable<decimal> Meter_Factor { get; set; }
        public string Temp_Comp_Meter { get; set; }
        public Nullable<System.DateTime> MeterProvingDate { get; set; }
    
        public virtual tankmodel tankmodel { get; set; }
    }
}
