//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_service_variance
    {
        public int csv_id { get; set; }
        public string cmp_id { get; set; }
        public Nullable<int> csv_pup_early { get; set; }
        public Nullable<int> csv_pup_late { get; set; }
        public Nullable<int> csv_del_early { get; set; }
        public Nullable<int> csv_del_late { get; set; }
        public Nullable<int> csv_billto_early { get; set; }
        public Nullable<int> csv_billto_late { get; set; }
        public Nullable<System.DateTime> eff_date_start { get; set; }
        public Nullable<System.DateTime> eff_date_end { get; set; }
        public Nullable<System.DateTime> created_dt { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> last_updateddt { get; set; }
        public string last_updatedby { get; set; }
    }
}
