//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_PropertyRights
    {
        public string id { get; set; }
        public string objt_objectid { get; set; }
        public string objt_propertyname { get; set; }
        public string grp_groupid { get; set; }
        public bool writebln { get; set; }
        public bool readbln { get; set; }
        public byte[] timestampq { get; set; }
    }
}
