//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_lanetariff
    {
        public int LaneId { get; set; }
        public string BillTo { get; set; }
        public string BillToParent { get; set; }
        public string OrderBy { get; set; }
        public string RevType1 { get; set; }
        public string RevType2 { get; set; }
        public string RevType3 { get; set; }
        public string RevType4 { get; set; }
        public string LghType1 { get; set; }
        public string LghType2 { get; set; }
        public string Terms { get; set; }
        public string TrlType1 { get; set; }
        public string TrlType2 { get; set; }
        public string TrlType3 { get; set; }
        public string TrlType4 { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityClass { get; set; }
        public string FlatPayType { get; set; }
        public string PerMilePayType { get; set; }
    
        public virtual core_lane core_lane { get; set; }
    }
}
