//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class core_lane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public core_lane()
        {
            this.core_lanefilter = new HashSet<core_lanefilter>();
        }
    
        public int laneid { get; set; }
        public string lanecode { get; set; }
        public string lanename { get; set; }
        public byte[] timestamp { get; set; }
        public Nullable<System.DateTime> updatedt { get; set; }
        public string updatedby { get; set; }
        public string yn_carrierhub { get; set; }
        public string RateMode { get; set; }
        public string UseCarrierConnect { get; set; }
        public string LaneSource { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<core_lanefilter> core_lanefilter { get; set; }
        public virtual core_lanetariff core_lanetariff { get; set; }
    }
}
