//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public string code { get; set; }
        public string name { get; set; }
        public byte postcode_routing { get; set; }
        public byte postcode_billing { get; set; }
        public Nullable<short> timezone_offset { get; set; }
        public string VAT_country { get; set; }
        public byte sunday { get; set; }
        public string sunday_open_shipping1 { get; set; }
        public string sunday_close_shipping1 { get; set; }
        public string sunday_open_receiving1 { get; set; }
        public string sunday_close_receiving1 { get; set; }
        public string sunday_open_shipping2 { get; set; }
        public string sunday_close_shipping2 { get; set; }
        public string sunday_open_receiving2 { get; set; }
        public string sunday_close_receiving2 { get; set; }
        public byte monday { get; set; }
        public string monday_open_shipping1 { get; set; }
        public string monday_close_shipping1 { get; set; }
        public string monday_open_receiving1 { get; set; }
        public string monday_close_receiving1 { get; set; }
        public string monday_open_shipping2 { get; set; }
        public string monday_close_shipping2 { get; set; }
        public string monday_open_receiving2 { get; set; }
        public string monday_close_receiving2 { get; set; }
        public byte tuesday { get; set; }
        public string tuesday_open_shipping1 { get; set; }
        public string tuesday_close_shipping1 { get; set; }
        public string tuesday_open_receiving1 { get; set; }
        public string tuesday_close_receiving1 { get; set; }
        public string tuesday_open_shipping2 { get; set; }
        public string tuesday_close_shipping2 { get; set; }
        public string tuesday_open_receiving2 { get; set; }
        public string tuesday_close_receiving2 { get; set; }
        public byte wednesday { get; set; }
        public string wednesday_open_shipping1 { get; set; }
        public string wednesday_close_shipping1 { get; set; }
        public string wednesday_open_receiving1 { get; set; }
        public string wednesday_close_receiving1 { get; set; }
        public string wednesday_open_shipping2 { get; set; }
        public string wednesday_close_shipping2 { get; set; }
        public string wednesday_open_receiving2 { get; set; }
        public string wednesday_close_receiving2 { get; set; }
        public byte thursday { get; set; }
        public string thursday_open_shipping1 { get; set; }
        public string thursday_close_shipping1 { get; set; }
        public string thursday_open_receiving1 { get; set; }
        public string thursday_close_receiving1 { get; set; }
        public string thursday_open_shipping2 { get; set; }
        public string thursday_close_shipping2 { get; set; }
        public string thursday_open_receiving2 { get; set; }
        public string thursday_close_receiving2 { get; set; }
        public byte friday { get; set; }
        public string friday_open_shipping1 { get; set; }
        public string friday_close_shipping1 { get; set; }
        public string friday_open_receiving1 { get; set; }
        public string friday_close_receiving1 { get; set; }
        public string friday_open_shipping2 { get; set; }
        public string friday_close_shipping2 { get; set; }
        public string friday_open_receiving2 { get; set; }
        public string friday_close_receiving2 { get; set; }
        public byte saturday { get; set; }
        public string saturday_open_shipping1 { get; set; }
        public string saturday_close_shipping1 { get; set; }
        public string saturday_open_receiving1 { get; set; }
        public string saturday_close_receiving1 { get; set; }
        public string saturday_open_shipping2 { get; set; }
        public string saturday_close_shipping2 { get; set; }
        public string saturday_open_receiving2 { get; set; }
        public string saturday_close_receiving2 { get; set; }
        public string currency { get; set; }
        public string currencysymbol { get; set; }
        public string decimal_indicator { get; set; }
        public string thousand_indicator { get; set; }
        public string symbol_placement { get; set; }
        public string isocode { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public string updatedby { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public byte def_country { get; set; }
        public byte eu_country { get; set; }
        public string doc_language { get; set; }
        public Nullable<short> min_postcodelen { get; set; }
        public Nullable<short> max_postcodelen { get; set; }
        public string customs_countrycode { get; set; }
        public short decimal_places { get; set; }
        public string phone_format { get; set; }
    }
}
