//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_dictionary
    {
        public string ddy_tblnam { get; set; }
        public string ddy_colnam { get; set; }
        public string ddy_coldsc { get; set; }
        public string ddy_colsysctlid { get; set; }
        public string ddy_colminmax { get; set; }
        public string ddy_coldefval { get; set; }
        public string ddy_colden { get; set; }
        public string ddy_colprikey { get; set; }
        public string ddy_colfgnkey { get; set; }
        public string ddy_coliniscn { get; set; }
        public string ddy_collbl { get; set; }
        public string ddy_collblcodrng { get; set; }
        public string ddy_colcom { get; set; }
    }
}
