//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dedbillingschedule_tariffs
    {
        public int dbst_id { get; set; }
        public int dbs_id { get; set; }
        public int dbse_id { get; set; }
        public Nullable<int> tar_number { get; set; }
        public Nullable<int> trk_number { get; set; }
        public Nullable<int> dbst_rollinto_tar { get; set; }
    }
}
