//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dedbillingscheduleentity
    {
        public int dbse_id { get; set; }
        public Nullable<int> dbs_id { get; set; }
        public string ord_billto { get; set; }
        public string ord_revtype1 { get; set; }
        public string ord_revtype2 { get; set; }
        public string ord_revtype3 { get; set; }
        public string ord_revtype4 { get; set; }
        public string ord_booked_revtype1 { get; set; }
        public string dbse_use_selected_invoices { get; set; }
        public string dbse_usedate { get; set; }
        public Nullable<int> dbse_priority { get; set; }
        public string dbse_override_output_flag { get; set; }
        public string dbse_action { get; set; }
        public string dbse_emailflag { get; set; }
        public string dbse_email { get; set; }
        public string dbse_printflag { get; set; }
        public string dbse_printer { get; set; }
        public string dbse_fileflag { get; set; }
        public string dbse_filedirectory { get; set; }
        public string dbse_printformattype { get; set; }
        public Nullable<int> ir_id { get; set; }
        public Nullable<int> irk_id { get; set; }
        public Nullable<int> dbg_id_print { get; set; }
        public Nullable<int> dbg_id_aggregate { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_user { get; set; }
        public Nullable<System.DateTime> dbse_cutoff_time { get; set; }
        public string dbse_applyall_rates { get; set; }
        public string ivh_splitgroup { get; set; }
    }
}
