//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DedicatedContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DedicatedContract()
        {
            this.DedicatedAggregateRates = new HashSet<DedicatedAggregateRate>();
            this.DedicatedContractRestrictions = new HashSet<DedicatedContractRestriction>();
            this.DedicatedRates = new HashSet<DedicatedRate>();
        }
    
        public int ContractId { get; set; }
        public string BillToId { get; set; }
        public string Description { get; set; }
        public System.DateTime ContractStart { get; set; }
        public Nullable<System.DateTime> ContractEnd { get; set; }
        public int BillUseDate { get; set; }
        public int ScheduleId { get; set; }
        public Nullable<int> OutputRestrictionId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DedicatedAggregateRate> DedicatedAggregateRates { get; set; }
        public virtual DedicatedContractBillUseDate DedicatedContractBillUseDate { get; set; }
        public virtual Schedule Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DedicatedContractRestriction> DedicatedContractRestrictions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DedicatedRate> DedicatedRates { get; set; }
    }
}
