//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class delayincident
    {
        public int di_id { get; set; }
        public Nullable<int> lgh_number { get; set; }
        public Nullable<int> ord_hdrnumber { get; set; }
        public Nullable<int> di_prev_stp_number { get; set; }
        public Nullable<int> di_next_stp_number { get; set; }
        public Nullable<int> di_prev_stp_sequence { get; set; }
        public Nullable<int> di_next_stp_sequence { get; set; }
        public string di_delaytype { get; set; }
        public string di_delayreason { get; set; }
        public string di_delay_explanation { get; set; }
        public Nullable<int> di_delay_min { get; set; }
        public Nullable<System.DateTime> di_delay_starttime { get; set; }
        public Nullable<System.DateTime> di_delay_endtime { get; set; }
        public Nullable<int> pyd_number { get; set; }
        public Nullable<int> ivd_number { get; set; }
    }
}
