//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dhl_payment_data
    {
        public int pad_batch { get; set; }
        public int pad_identity { get; set; }
        public string pad_number { get; set; }
        public string pad_payment_date { get; set; }
        public string pad_payment_doc_number { get; set; }
    }
}
