//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverRetentionConfiguration
    {
        public int ID { get; set; }
        public string CustomerId { get; set; }
        public string AuthenticationUrl { get; set; }
        public string RetentionUrl { get; set; }
        public string ConsumerKey { get; set; }
        public bool UseAlternateId { get; set; }
    }
}
