//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class driverdocument
    {
        public string mpp_id { get; set; }
        public string drd_doctype { get; set; }
        public string drd_docnumber { get; set; }
        public string drd_stateofissue { get; set; }
        public string drd_countryofissue { get; set; }
        public string drd_default { get; set; }
        public string drd_type { get; set; }
    }
}
