//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dx_BusinessRules
    {
        public long dx_ident { get; set; }
        public Nullable<int> dx_ExecGroup { get; set; }
        public string dx_TradingPartnerID { get; set; }
        public string dx_importid { get; set; }
        public string dx_rulename { get; set; }
        public Nullable<int> dx_ruleExecSequence { get; set; }
        public Nullable<int> dx_recordseq { get; set; }
        public string dx_which { get; set; }
        public string dx_item { get; set; }
        public string dx_field { get; set; }
        public string dx_operator { get; set; }
        public string dx_value { get; set; }
        public string dx_action { get; set; }
        public string dx_conjunction { get; set; }
        public string dx_ruletext { get; set; }
        public Nullable<System.DateTime> dx_lastupdated { get; set; }
        public string dx_lastuser { get; set; }
        public string dx_notifymessage { get; set; }
    }
}
