//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dx_QueueEvent
    {
        public int qev_Ident { get; set; }
        public string que_ID { get; set; }
        public string qev_Action { get; set; }
        public Nullable<System.DateTime> qev_Time { get; set; }
        public string qev_Detail { get; set; }
    
        public virtual dx_Queues dx_Queues { get; set; }
    }
}
