//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDI_214_FaxFormat
    {
        public Nullable<int> Format_ID { get; set; }
        public string Format_Name { get; set; }
        public string Active_Flag { get; set; }
        public string Subject_text { get; set; }
        public string Subject_Available_Flag { get; set; }
        public string Comment_text { get; set; }
        public string Comment_Available_Flag { get; set; }
    }
}
