//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class edi_outbound204_fgt
    {
        public Nullable<int> ob_204id { get; set; }
        public Nullable<int> ord_hdrnumber { get; set; }
        public Nullable<int> stp_number { get; set; }
        public Nullable<int> fgt_number { get; set; }
        public Nullable<int> fgt_sequence { get; set; }
        public Nullable<decimal> fgt_count { get; set; }
        public string fgt_countunit { get; set; }
        public Nullable<double> fgt_weight { get; set; }
        public string fgt_weightunit { get; set; }
        public Nullable<double> fgt_volume { get; set; }
        public string fgt_volumeunit { get; set; }
        public Nullable<decimal> fgt_rate { get; set; }
        public string fgt_rateunit { get; set; }
        public Nullable<decimal> fgt_charge { get; set; }
        public string cmd_code { get; set; }
        public string fgt_description { get; set; }
        public Nullable<double> fgt_actual_quantity { get; set; }
        public string fgt_actual_unit { get; set; }
        public string edi_commodity { get; set; }
        public string commodity_stcc { get; set; }
        public string cmd_haz_num { get; set; }
        public string fgt_hazmat_class_qualifier { get; set; }
        public string fgt_hazmat_shipping_name_qualifier { get; set; }
        public string shipping_name { get; set; }
        public string cmd_imdg_class { get; set; }
        public string cmd_imdg_packaginggroup { get; set; }
        public int edi_outbound204_fgt_ident { get; set; }
    }
}
