//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class efs_account
    {
        public string efs_account_number { get; set; }
        public string efs_auto_update_trip_flag { get; set; }
        public string efs_auto_unassign_trip_flag { get; set; }
        public string efs_auto_update_tractor_flag { get; set; }
        public string efs_auto_unassign_tractor_flag { get; set; }
        public string efs_auto_update_trailer_flag { get; set; }
        public string efs_auto_unassign_trailer_flag { get; set; }
        public string efs_auto_update_driver_flag { get; set; }
        public string efs_auto_unassign_driver_flag { get; set; }
        public string efs_inactive_trip_card_status { get; set; }
        public string efs_default_assignment { get; set; }
        public Nullable<System.DateTime> efs_updated_on { get; set; }
        public string efs_updated_by { get; set; }
        public Nullable<System.DateTime> efs_created_date { get; set; }
    }
}
