//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class emailaddress
    {
        public int em_id { get; set; }
        public string em_address { get; set; }
        public string em_valid_time_begin { get; set; }
        public string em_valid_time_end { get; set; }
        public Nullable<short> em_occurrence_level { get; set; }
    }
}
