//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipmentconfigheader
    {
        public int ech_id { get; set; }
        public string ech_trc_loading_class { get; set; }
        public string ech_lead_trl_loading_class { get; set; }
        public string ech_pup_trl_loading_class { get; set; }
        public string ech_train_config { get; set; }
        public string ech_trc_front_axl_type { get; set; }
        public string ech_trc_rear_axl_type { get; set; }
        public string ech_lead_trl_front_axl_type { get; set; }
        public string ech_lead_trl_rear_axl_type { get; set; }
        public string ech_pup_trl_front_axl_type { get; set; }
        public string ech_pup_trl_rear_axl_type { get; set; }
        public Nullable<int> ech_trc_compartm_number { get; set; }
        public Nullable<int> ech_lead_trl_compartm_number { get; set; }
        public Nullable<int> ech_pup_trl_compartm_number { get; set; }
        public Nullable<short> ech_axles { get; set; }
        public string cmd_class { get; set; }
    }
}
