//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class estatScheduledCSRptSummaryOption
    {
        public int rpt_sched_id { get; set; }
        public string UserName { get; set; }
        public string Clientid { get; set; }
        public string CompanyType { get; set; }
        public string ReportLevel { get; set; }
        public string ToleranceLateUnit { get; set; }
        public string ToleranceEarlyUnit { get; set; }
        public string ToleranceLate { get; set; }
        public string ToleranceEarly { get; set; }
    }
}
