//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventcustomstl
    {
        public int evt_number { get; set; }
        public int evtcs_row_type { get; set; }
        public Nullable<int> evtcs_trip_number { get; set; }
        public Nullable<int> evtcs_line_number { get; set; }
        public Nullable<decimal> evtcs_delivery_time { get; set; }
        public Nullable<decimal> evtcs_delivery_time_rounded { get; set; }
        public Nullable<int> sdd_id { get; set; }
        public System.DateTime evtcs_created_date { get; set; }
        public string evtcs_created_user { get; set; }
        public System.DateTime evtcs_modified_date { get; set; }
        public string evtcs_modified_user { get; set; }
    }
}
