//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventviewdetail
    {
        public int evd_number { get; set; }
        public Nullable<int> evh_number { get; set; }
        public Nullable<int> evd_seq { get; set; }
        public string evd_eventcode { get; set; }
        public Nullable<int> evd_est_red { get; set; }
        public Nullable<int> evd_est_green { get; set; }
        public Nullable<int> evd_est_blue { get; set; }
        public Nullable<int> evd_act_red { get; set; }
        public Nullable<int> evd_act_green { get; set; }
        public Nullable<int> evd_act_blue { get; set; }
        public Nullable<int> evd_deftime { get; set; }
        public string evd_defevent { get; set; }
    }
}
