//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class expedite_audit_activities
    {
        public int eaa_id { get; set; }
        public string eaa_application { get; set; }
        public string eaa_userid { get; set; }
        public string eaa_activity { get; set; }
        public string eaa_exclude { get; set; }
    }
}
