//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class expiration
    {
        public string exp_idtype { get; set; }
        public string exp_id { get; set; }
        public string exp_code { get; set; }
        public Nullable<System.DateTime> exp_lastdate { get; set; }
        public Nullable<System.DateTime> exp_expirationdate { get; set; }
        public string exp_routeto { get; set; }
        public string exp_completed { get; set; }
        public string exp_priority { get; set; }
        public Nullable<System.DateTime> exp_compldate { get; set; }
        public byte[] timestamp { get; set; }
        public string exp_updateby { get; set; }
        public Nullable<System.DateTime> exp_creatdate { get; set; }
        public Nullable<System.DateTime> exp_updateon { get; set; }
        public string exp_description { get; set; }
        public Nullable<int> exp_milestoexp { get; set; }
        public int exp_key { get; set; }
        public Nullable<int> exp_city { get; set; }
        public Nullable<int> mov_number { get; set; }
        public string exp_control_avl_date { get; set; }
        public Nullable<byte> skip_trigger { get; set; }
        public string exp_auto_created { get; set; }
        public string exp_source { get; set; }
        public Nullable<int> cai_id { get; set; }
        public string exp_recurrence { get; set; }
        public Nullable<int> carriercsalogdtl_id { get; set; }
        public Nullable<int> exp_duration { get; set; }
        public Nullable<System.DateTime> exp_acceptable_start { get; set; }
        public Nullable<System.DateTime> exp_acceptable_end { get; set; }
        public Nullable<int> trlStgID { get; set; }
    
        public virtual CarrierCSALogDtl CarrierCSALogDtl { get; set; }
        public virtual TrlStorage TrlStorage { get; set; }
    }
}
