//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fbi_interfaces
    {
        public int fbii_id { get; set; }
        public string fbii_code { get; set; }
        public string fbii_desc { get; set; }
        public string fbii_license_key { get; set; }
        public string fbii_license_key2 { get; set; }
    }
}
