//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fixedrouterotating
    {
        public int frr_id { get; set; }
        public int frr_sequence { get; set; }
        public string frr_enabled { get; set; }
        public string frr_dow1 { get; set; }
        public string frr_dow2 { get; set; }
        public string frr_dow3 { get; set; }
        public string frr_dow4 { get; set; }
        public string frr_dow5 { get; set; }
        public string frr_dow6 { get; set; }
        public string frr_dow7 { get; set; }
    }
}
