//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class freightdetail
    {
        public int fgt_number { get; set; }
        public string cmd_code { get; set; }
        public Nullable<double> fgt_weight { get; set; }
        public string fgt_weightunit { get; set; }
        public string fgt_description { get; set; }
        public Nullable<int> stp_number { get; set; }
        public Nullable<decimal> fgt_count { get; set; }
        public string fgt_countunit { get; set; }
        public Nullable<double> fgt_volume { get; set; }
        public string fgt_volumeunit { get; set; }
        public Nullable<short> fgt_lowtemp { get; set; }
        public Nullable<short> fgt_hitemp { get; set; }
        public Nullable<short> fgt_sequence { get; set; }
        public Nullable<double> fgt_length { get; set; }
        public string fgt_lengthunit { get; set; }
        public Nullable<double> fgt_height { get; set; }
        public string fgt_heightunit { get; set; }
        public Nullable<double> fgt_width { get; set; }
        public string fgt_widthunit { get; set; }
        public byte[] timestamp { get; set; }
        public string fgt_reftype { get; set; }
        public string fgt_refnum { get; set; }
        public Nullable<double> fgt_quantity { get; set; }
        public Nullable<decimal> fgt_rate { get; set; }
        public Nullable<decimal> fgt_charge { get; set; }
        public string fgt_rateunit { get; set; }
        public string cht_itemcode { get; set; }
        public string cht_basisunit { get; set; }
        public string fgt_unit { get; set; }
        public Nullable<byte> skip_trigger { get; set; }
        public Nullable<double> tare_weight { get; set; }
        public string tare_weightunit { get; set; }
        public Nullable<double> fgt_pallets_in { get; set; }
        public Nullable<double> fgt_pallets_out { get; set; }
        public Nullable<double> fgt_pallets_on_trailer { get; set; }
        public Nullable<double> fgt_carryins1 { get; set; }
        public Nullable<double> fgt_carryins2 { get; set; }
        public string fgt_stackable { get; set; }
        public Nullable<double> fgt_ratingquantity { get; set; }
        public string fgt_ratingunit { get; set; }
        public Nullable<short> fgt_quantity_type { get; set; }
        public Nullable<float> fgt_ordered_count { get; set; }
        public Nullable<double> fgt_ordered_weight { get; set; }
        public Nullable<int> tar_number { get; set; }
        public string tar_tariffnumber { get; set; }
        public string tar_tariffitem { get; set; }
        public Nullable<short> fgt_charge_type { get; set; }
        public Nullable<short> fgt_rate_type { get; set; }
        public Nullable<decimal> fgt_ordered_volume { get; set; }
        public Nullable<decimal> fgt_ordered_loadingmeters { get; set; }
        public string fgt_pallet_type { get; set; }
        public Nullable<decimal> fgt_loadingmeters { get; set; }
        public string fgt_loadingmetersunit { get; set; }
        public string fgt_additionl_description { get; set; }
        public Nullable<double> fgt_specific_flashpoint { get; set; }
        public string fgt_specific_flashpoint_unit { get; set; }
        public string fgt_tmstatus { get; set; }
        public Nullable<decimal> cpr_density { get; set; }
        public string scm_subcode { get; set; }
        public string fgt_consignee { get; set; }
        public string fgt_shipper { get; set; }
        public string fgt_billto { get; set; }
        public string fgt_terms { get; set; }
        public string fgt_leg_origin { get; set; }
        public string fgt_leg_dest { get; set; }
        public Nullable<decimal> fgt_count2 { get; set; }
        public string fgt_count2unit { get; set; }
        public Nullable<int> fgt_bolid { get; set; }
        public string fgt_bol_status { get; set; }
        public string fgt_osdreason { get; set; }
        public Nullable<int> fgt_osdquantity { get; set; }
        public string fgt_osdunit { get; set; }
        public string fgt_osdcomment { get; set; }
        public string fgt_packageunit { get; set; }
        public string fgt_osdstatus { get; set; }
        public Nullable<System.DateTime> fgt_osdopendate { get; set; }
        public Nullable<System.DateTime> fgt_osdclosedate { get; set; }
        public Nullable<decimal> fgt_osdorigclaimamount { get; set; }
        public Nullable<decimal> fgt_osdamtpaid { get; set; }
        public Nullable<decimal> fgt_osdamtreceived { get; set; }
        public Nullable<double> fgt_dispatched_quantity { get; set; }
        public string fgt_dispatched_unit { get; set; }
        public Nullable<double> fgt_actual_quantity { get; set; }
        public string fgt_actual_unit { get; set; }
        public Nullable<double> fgt_billable_quantity { get; set; }
        public string fgt_billable_unit { get; set; }
        public string fgt_supplier { get; set; }
        public Nullable<int> fgt_parentcmd_fgt_number { get; set; }
        public Nullable<int> fgt_display_sequence { get; set; }
        public string fgt_accountof { get; set; }
        public Nullable<double> fgt_volume2 { get; set; }
        public string fgt_volume2unit { get; set; }
        public string fgt_pincode { get; set; }
        public Nullable<int> fgt_parentcmd_number { get; set; }
        public string fgt_bol_image { get; set; }
        public Nullable<System.DateTime> fgt_bol_image_date { get; set; }
        public string fgt_volumeunit2 { get; set; }
        public string tank_loc { get; set; }
        public Nullable<double> fgt_deliverytank1 { get; set; }
        public Nullable<double> fgt_deliverytank2 { get; set; }
        public Nullable<double> fgt_deliverytank3 { get; set; }
        public Nullable<double> fgt_deliverytank4 { get; set; }
        public Nullable<double> fgt_deliverytank5 { get; set; }
        public Nullable<double> fgt_deliverytank6 { get; set; }
        public Nullable<double> fgt_deliverytank7 { get; set; }
        public Nullable<double> fgt_deliverytank8 { get; set; }
        public Nullable<double> fgt_deliverytank9 { get; set; }
        public Nullable<double> fgt_deliverytank10 { get; set; }
        public string fgt_asset { get; set; }
        public string fgt_tempunit { get; set; }
        public Nullable<int> fgt_number_copied_fromorder { get; set; }
        public string fgt_hazmat_class_qualifier { get; set; }
        public string fgt_hazmat_shipping_name_qualifier { get; set; }
        public Nullable<decimal> fgt_size { get; set; }
        public Nullable<int> order_hdrnumber { get; set; }
        public string fgt_app_eqcodes { get; set; }
    }
}
