//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelTaxMileageDetail
    {
        public int ftm_recid { get; set; }
        public int lgh_number { get; set; }
        public string ftm_state { get; set; }
        public decimal ftm_freemiles { get; set; }
        public decimal ftm_tollmiles { get; set; }
        public decimal ftm_totalmiles { get; set; }
        public Nullable<decimal> ftm_tollcost { get; set; }
        public System.DateTime ftm_date { get; set; }
        public string ftm_entrytype { get; set; }
        public string ftm_reprocess { get; set; }
        public string ftm_status { get; set; }
        public System.DateTime ftm_createdate { get; set; }
        public string ftm_createdby { get; set; }
        public Nullable<System.DateTime> ftm_updatedate { get; set; }
        public string ftm_updatedby { get; set; }
    }
}
