//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fuel_intraday_packets
    {
        public int id { get; set; }
        public int xfacetype { get; set; }
        public string transaction_data { get; set; }
        public System.DateTime transaction_date { get; set; }
        public Nullable<int> transaction_number { get; set; }
        public string status { get; set; }
        public string error_message { get; set; }
        public string extra_data { get; set; }
        public Nullable<System.DateTime> created_datetime { get; set; }
        public Nullable<System.DateTime> processed_datetime { get; set; }
        public System.DateTime last_updated_datetime { get; set; }
        public string last_updated_by { get; set; }
    }
}
