//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fuelticket_updatelog
    {
        public int ftk_ticket_number { get; set; }
        public System.DateTime ftk_updated_on { get; set; }
        public string ftk_updated_by { get; set; }
        public int ftk_old_ord_hdrnumber { get; set; }
        public Nullable<int> ftk_old_mov_number { get; set; }
    }
}
