//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fuelagent_log
    {
        public int fal_id { get; set; }
        public Nullable<int> gf_request_id { get; set; }
        public int gf_lgh_number { get; set; }
        public string fal_type { get; set; }
        public string fal_message { get; set; }
        public string fal_updatedby { get; set; }
        public Nullable<System.DateTime> fal_time { get; set; }
    }
}
