//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fueltax_export
    {
        public int BatchID { get; set; }
        public Nullable<int> lgh_number { get; set; }
        public Nullable<System.DateTime> lgh_startdate { get; set; }
        public Nullable<int> mov_number { get; set; }
        public string lgh_tractor { get; set; }
        public Nullable<System.DateTime> stp_arrivaldate { get; set; }
        public Nullable<System.DateTime> stp_departuredate { get; set; }
        public string stp_type { get; set; }
        public string alk_city { get; set; }
        public string cty_name { get; set; }
        public string alk_state { get; set; }
        public string cty_state { get; set; }
        public string cty_zip { get; set; }
        public string fp_id { get; set; }
        public Nullable<int> fp_sequence { get; set; }
        public string ord_number { get; set; }
        public Nullable<System.DateTime> fp_date { get; set; }
        public Nullable<decimal> fp_amount { get; set; }
        public string fp_invoice_no { get; set; }
        public string fp_vendorname { get; set; }
        public string fp_uom { get; set; }
        public Nullable<double> fp_quantity { get; set; }
        public string fp_purchcode { get; set; }
        public Nullable<int> lgh_ord_hdrnumber { get; set; }
        public string trc_type1 { get; set; }
        public string trc_type2 { get; set; }
        public string trc_type3 { get; set; }
        public string trc_type4 { get; set; }
        public Nullable<int> stp_city { get; set; }
        public string lgh_driver1 { get; set; }
        public Nullable<int> latitude { get; set; }
        public Nullable<int> longitude { get; set; }
        public string stp_loadstatus { get; set; }
        public string gpstype { get; set; }
        public Nullable<int> lgh_odometerstart { get; set; }
        public Nullable<int> lgh_odometerend { get; set; }
        public Nullable<int> stp_mfh_sequence { get; set; }
        public string stp_event { get; set; }
        public Nullable<int> stp_lgh_mileage { get; set; }
        public string ord_revtype2 { get; set; }
        public string ord_revtype1 { get; set; }
        public string evt_trailer1 { get; set; }
        public string evt_trailer2 { get; set; }
        public Nullable<int> stp_number { get; set; }
        public string cmp_id { get; set; }
        public string tmp_ordnumber { get; set; }
        public string trc_company { get; set; }
        public string final_loadedstatus { get; set; }
        public string lgh_type1 { get; set; }
        public string OrigDestFlag { get; set; }
        public string county { get; set; }
        public string ALK_county { get; set; }
        public string Rand_county { get; set; }
        public Nullable<double> cty_GMTDelta { get; set; }
        public string cty_DSTApplies { get; set; }
        public string fp_fueltype { get; set; }
        public string fp_cost_per { get; set; }
        public string ckc_updatedby { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<System.DateTime> TransferDateTime { get; set; }
        public int SN { get; set; }
        public Nullable<int> SortSN { get; set; }
        public string rand_city { get; set; }
        public string rand_state { get; set; }
    }
}
