//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class gl_posting_matrix
    {
        public string glpm_booked_terminal { get; set; }
        public string glpm_executing_terminal { get; set; }
        public string glpm_revenue_gl { get; set; }
        public string glpm_cost_gl { get; set; }
    }
}
