//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class gp_trcrental
    {
        public int trcr_id { get; set; }
        public string trcr_loan_cmp { get; set; }
        public string trcr_borrow_cmp { get; set; }
        public string trcr_loan_term { get; set; }
        public string trcr_borrow_term { get; set; }
        public Nullable<int> trcr_min_age { get; set; }
        public Nullable<int> trcr_max_age { get; set; }
        public Nullable<decimal> trcr_rent_var { get; set; }
        public Nullable<decimal> trcr_rent_fix { get; set; }
        public string trcr_CompTerm { get; set; }
    }
}
