//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class gpunit
    {
        public string company { get; set; }
        public string type { get; set; }
        public string account { get; set; }
        public string usertype { get; set; }
        public string uservalue { get; set; }
    }
}
