//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HydraScheduleOccurrence
    {
        public int ID { get; set; }
        public string Job_Name { get; set; }
        public int Job_SchUnit { get; set; }
        public string Job_SchUnitType { get; set; }
        public Nullable<System.DateTime> Job_SchStartTime { get; set; }
        public Nullable<System.DateTime> Job_SchEndTime { get; set; }
        public string Sunday { get; set; }
        public string Monday { get; set; }
        public string Tuesday { get; set; }
        public string Wednesday { get; set; }
        public string Thursday { get; set; }
        public string Friday { get; set; }
        public string Saturday { get; set; }
    
        public virtual HydraJob HydraJob { get; set; }
    }
}
