//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HydraLog
    {
        public int ID { get; set; }
        public string Job_Name { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string MessageType { get; set; }
        public string Messagetext { get; set; }
    }
}
