//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class im_iso_codes
    {
        public string iso_code { get; set; }
        public string description { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> height { get; set; }
        public string trl_type1 { get; set; }
        public string trl_type2 { get; set; }
        public string trl_type3 { get; set; }
        public string trl_type4 { get; set; }
        public Nullable<int> max_pallets { get; set; }
        public Nullable<decimal> max_weight { get; set; }
        public Nullable<decimal> max_volume { get; set; }
        public byte[] rowchgts { get; set; }
    }
}
