//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENT
    {
        public int inc_ID { get; set; }
        public int srp_ID { get; set; }
        public byte inc_Sequence { get; set; }
        public string inc_MppOrEeID { get; set; }
        public Nullable<System.DateTime> inc_ReportedDate { get; set; }
        public string inc_ReceivedBy { get; set; }
        public string inc_HandledBy { get; set; }
        public string inc_TicketIssued { get; set; }
        public string inc_TrafficViolation { get; set; }
        public Nullable<byte> inc_Points { get; set; }
        public string inc_IncidentType1 { get; set; }
        public string inc_IncidentType2 { get; set; }
        public string inc_Description { get; set; }
        public string inc_Comment { get; set; }
        public string inc_ComplaintantIs { get; set; }
        public string inc_EEComplaintant { get; set; }
        public string inc_ComplCmpID { get; set; }
        public string inc_ComplName { get; set; }
        public string inc_ComplAddress1 { get; set; }
        public string inc_ComplAddress2 { get; set; }
        public Nullable<int> inc_ComplCity { get; set; }
        public string inc_ComplCtynmstct { get; set; }
        public string inc_ComplState { get; set; }
        public string inc_ComplZip { get; set; }
        public string inc_ComplCountry { get; set; }
        public string inc_ComplHomePhone { get; set; }
        public string inc_ComplWorkPhone { get; set; }
        public string inc_FollowUpRequired { get; set; }
        public string inc_FollowUpDesc { get; set; }
        public string inc_FollowUpCompleted { get; set; }
        public Nullable<System.DateTime> inc_FollowUpCompletedDate { get; set; }
        public string inc_LawEnfDeptName { get; set; }
        public string inc_LawEnfDeptAddress { get; set; }
        public Nullable<int> inc_LawEnfDeptCity { get; set; }
        public string inc_LawEnfDeptCtynmstct { get; set; }
        public string inc_LawEnfDeptState { get; set; }
        public string inc_LawEnfDeptCountry { get; set; }
        public string inc_LawEnfDeptZip { get; set; }
        public string inc_LawEnfDeptPhone { get; set; }
        public string inc_LawEnfOfficer { get; set; }
        public string inc_LawEnfOfficerBadge { get; set; }
        public string inc_PoliceReportNumber { get; set; }
        public string inc_TicketIssuedTo { get; set; }
        public string inc_TicketDesc { get; set; }
        public string inc_CKBox1 { get; set; }
        public string inc_CKBox2 { get; set; }
        public string inc_CKBox3 { get; set; }
        public string inc_CKBox4 { get; set; }
        public string inc_CKBox5 { get; set; }
        public string ord_number { get; set; }
        public string inc_driver1 { get; set; }
        public string inc_driver2 { get; set; }
        public string inc_tractor { get; set; }
        public string inc_trailer1 { get; set; }
        public string inc_trailer2 { get; set; }
        public string inc_carrier { get; set; }
        public Nullable<int> lgh_number { get; set; }
        public Nullable<int> mov_number { get; set; }
        public string inc_string1 { get; set; }
        public string inc_string2 { get; set; }
        public string inc_string3 { get; set; }
        public string inc_string4 { get; set; }
        public string inc_string5 { get; set; }
        public Nullable<decimal> inc_number1 { get; set; }
        public Nullable<decimal> inc_number2 { get; set; }
        public Nullable<decimal> inc_number3 { get; set; }
        public Nullable<decimal> inc_number4 { get; set; }
        public Nullable<decimal> inc_number5 { get; set; }
        public string inc_IncidentType3 { get; set; }
        public string inc_IncidentType4 { get; set; }
        public string inc_IncidentType5 { get; set; }
        public string inc_IncidentType6 { get; set; }
        public Nullable<System.DateTime> inc_date1 { get; set; }
        public Nullable<System.DateTime> inc_date2 { get; set; }
        public Nullable<System.DateTime> inc_date3 { get; set; }
        public Nullable<System.DateTime> inc_date4 { get; set; }
        public Nullable<System.DateTime> inc_date5 { get; set; }
        public string inc_bigstring1 { get; set; }
    }
}
