//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ini_xref_file_section
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ini_xref_file_section()
        {
            this.ini_xref_file_section_item = new HashSet<ini_xref_file_section_item>();
        }
    
        public int file_section_id { get; set; }
        public int file_id { get; set; }
        public int section_id { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public string active { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public string updated_by { get; set; }
        public string comment { get; set; }
    
        public virtual ini_file ini_file { get; set; }
        public virtual ini_section ini_section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ini_xref_file_section_item> ini_xref_file_section_item { get; set; }
    }
}
