//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ini_xref_group_user
    {
        public int group_user_id { get; set; }
        public System.DateTime created { get; set; }
        public string created_by { get; set; }
        public string active { get; set; }
        public Nullable<int> group_id { get; set; }
        public string usr_userid { get; set; }
        public Nullable<System.DateTime> updated { get; set; }
        public string updated_by { get; set; }
    
        public virtual ini_group ini_group { get; set; }
    }
}
