//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class INJURY
    {
        public int inj_ID { get; set; }
        public int srp_ID { get; set; }
        public byte inj_sequence { get; set; }
        public Nullable<System.DateTime> inj_ReportedDate { get; set; }
        public string inj_Description { get; set; }
        public string inj_Comment { get; set; }
        public string inj_HowOccurred { get; set; }
        public Nullable<System.DateTime> inj_DateOfFullRelease { get; set; }
        public string inj_PersonIs { get; set; }
        public string inj_MppOrEeID { get; set; }
        public string inj_Name { get; set; }
        public string inj_Address1 { get; set; }
        public string inj_Address2 { get; set; }
        public Nullable<int> inj_City { get; set; }
        public string inj_Ctynmstct { get; set; }
        public string inj_State { get; set; }
        public string inj_zip { get; set; }
        public string inj_Country { get; set; }
        public string inj_HomePhone { get; set; }
        public string inj_WorkPhone { get; set; }
        public Nullable<System.DateTime> inj_LastDateWorked { get; set; }
        public Nullable<System.DateTime> inj_ExpectedReturn { get; set; }
        public string inj_ClaimInDoubt { get; set; }
        public string inj_InjuryType1 { get; set; }
        public string inj_InjuryType2 { get; set; }
        public string inj_IsFatal { get; set; }
        public string inj_TreatedAtScene { get; set; }
        public string inj_AtSceneCaregiver { get; set; }
        public string inj_TreatedAwayFromScene { get; set; }
        public string inj_ReportedToInsurance { get; set; }
        public Nullable<System.DateTime> inj_InsCoReportDate { get; set; }
        public string inj_maritalstatus { get; set; }
        public string inj_gender { get; set; }
        public Nullable<byte> inj_nbrdependents { get; set; }
        public Nullable<System.DateTime> inj_NextSchedAppt { get; set; }
        public Nullable<System.DateTime> inj_DateofBirth { get; set; }
        public string inj_ssn { get; set; }
        public string inj_workstate { get; set; }
        public string inj_occupation { get; set; }
        public string inj_medicalrestrictions { get; set; }
        public string inj_CKBox1 { get; set; }
        public string inj_CKBox2 { get; set; }
        public string inj_CKBox3 { get; set; }
        public string inj_CKBox4 { get; set; }
        public string inj_CKBox5 { get; set; }
        public string inj_string1 { get; set; }
        public string inj_string2 { get; set; }
        public string inj_string3 { get; set; }
        public string inj_string4 { get; set; }
        public string inj_string5 { get; set; }
        public Nullable<decimal> inj_number1 { get; set; }
        public Nullable<decimal> inj_number2 { get; set; }
        public Nullable<decimal> inj_number3 { get; set; }
        public Nullable<decimal> inj_number4 { get; set; }
        public Nullable<decimal> inj_number5 { get; set; }
        public Nullable<System.DateTime> inj_date1 { get; set; }
        public string inj_InjuryType3 { get; set; }
        public string inj_InjuryType4 { get; set; }
        public string inj_InjuryType5 { get; set; }
        public string inj_InjuryType6 { get; set; }
        public Nullable<System.DateTime> inj_date2 { get; set; }
        public Nullable<System.DateTime> inj_date3 { get; set; }
        public Nullable<System.DateTime> inj_date4 { get; set; }
        public Nullable<System.DateTime> inj_date5 { get; set; }
    }
}
