//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class integratedreportarg
    {
        public int ir_id { get; set; }
        public int ira_sequence { get; set; }
        public string ira_parameter { get; set; }
        public string ira_parameter_name { get; set; }
        public string ira_datatype { get; set; }
        public string ira_required { get; set; }
        public string ira_parameter_name_rpt { get; set; }
    }
}
