//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationServiceOptimizationRequestsLegHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IntegrationServiceOptimizationRequestsLegHeader()
        {
            this.IntegrationServiceOptimizationRequestsLoadDatas = new HashSet<IntegrationServiceOptimizationRequestsLoadData>();
            this.IntegrationServiceOptimizationRequestsOrderDatas = new HashSet<IntegrationServiceOptimizationRequestsOrderData>();
            this.IntegrationServiceOptimizationRequestsRequestStatus = new HashSet<IntegrationServiceOptimizationRequestsRequestStatu>();
        }
    
        public int Id { get; set; }
        public int OptimizationRequestId { get; set; }
        public int LegHeaderNumber { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public Nullable<int> OrderHeaderNumber { get; set; }
        public Nullable<int> OptimizedLegHeaderNumber { get; set; }
        public string ShipWithGroupName { get; set; }
        public Nullable<int> SendCommodityCode { get; set; }
        public Nullable<int> SendReferenceNumbers { get; set; }
        public string AdditionalInfo { get; set; }
        public string RouteId { get; set; }
        public string LoadId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
    
        public virtual IntegrationServiceOptimizationRequest IntegrationServiceOptimizationRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegrationServiceOptimizationRequestsLoadData> IntegrationServiceOptimizationRequestsLoadDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegrationServiceOptimizationRequestsOrderData> IntegrationServiceOptimizationRequestsOrderDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegrationServiceOptimizationRequestsRequestStatu> IntegrationServiceOptimizationRequestsRequestStatus { get; set; }
    }
}
