//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class integratedreportkit
    {
        public int irk_id { get; set; }
        public string irk_name { get; set; }
        public string irk_purpose { get; set; }
        public Nullable<int> irk_master_ir_id { get; set; }
        public Nullable<int> irk_email_ir_id { get; set; }
        public string irk_report_list { get; set; }
        public string irk_message_list { get; set; }
        public string irk_communication_list { get; set; }
        public string irk_post_process_type { get; set; }
        public string irk_post_process { get; set; }
        public string irk_default_subject { get; set; }
        public string irk_default_other_email { get; set; }
        public System.DateTime irk_created_date { get; set; }
        public string irk_created_user { get; set; }
        public Nullable<System.DateTime> irk_modified_date { get; set; }
        public string irk_modified_user { get; set; }
    }
}
