//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationServiceOptimizationRequestsRequestStatu
    {
        public int Id { get; set; }
        public int RequestLegHeadersId { get; set; }
        public int LegHeaderNumber { get; set; }
        public string OrderCreationIntegrationAPI { get; set; }
        public Nullable<System.DateTime> SendStart { get; set; }
        public Nullable<System.DateTime> SendEnd { get; set; }
        public Nullable<int> Sending { get; set; }
        public Nullable<decimal> ModelCreationDuration { get; set; }
        public Nullable<decimal> ModelSendDuration { get; set; }
        public Nullable<int> Sent { get; set; }
        public string SendingMessages { get; set; }
    
        public virtual IntegrationServiceOptimizationRequestsLegHeader IntegrationServiceOptimizationRequestsLegHeader { get; set; }
    }
}
