//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class integratedreportkitarg
    {
        public int ika_id { get; set; }
        public Nullable<int> ika_sequence { get; set; }
        public string ika_column_name { get; set; }
        public string ika_parameter { get; set; }
        public string ika_datatype { get; set; }
        public Nullable<int> irk_id_master { get; set; }
        public Nullable<int> irk_id_email { get; set; }
        public Nullable<int> iki_id { get; set; }
        public Nullable<int> irk_id { get; set; }
        public System.DateTime ika_created_date { get; set; }
        public string ika_created_user { get; set; }
        public Nullable<System.DateTime> ika_modified_date { get; set; }
        public string ika_modified_user { get; set; }
        public string ika_parameter_name { get; set; }
    }
}
