//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class integrated_rep_transaction
    {
        public string irt_name { get; set; }
        public string irt_logid { get; set; }
        public string irt_logpass { get; set; }
        public string irt_autocommit { get; set; }
        public string irt_database { get; set; }
        public string irt_server { get; set; }
        public string irt_dbms { get; set; }
        public string irt_dbparm { get; set; }
    }
}
