//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoicedetailpayment
    {
        public int ivdpymt_number { get; set; }
        public int ivdpymt_ivdnumber { get; set; }
        public string ivdpymt_Check_number { get; set; }
        public string ivdpymt_GPBatch { get; set; }
        public System.DateTime ivdpymt_Check_date { get; set; }
        public Nullable<decimal> ivdpymt_Amount_pd { get; set; }
        public int ivdpymt_ivhnumber { get; set; }
        public int ivdpymt_pydnumber { get; set; }
    }
}
