//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvServicesDeliveryGroupAssign
    {
        public string cmp_id { get; set; }
        public string DelGroup { get; set; }
        public string CanShortLoad { get; set; }
    
        public virtual company company { get; set; }
        public virtual InvServicesDeliveryGroup InvServicesDeliveryGroup { get; set; }
    }
}
