//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPTErrorTable
    {
        public int id_num { get; set; }
        public string ipt_number { get; set; }
        public string orig_company { get; set; }
        public string dest_company { get; set; }
        public string ord_billto { get; set; }
        public string cmd_code { get; set; }
        public string trl_id { get; set; }
        public string err_text { get; set; }
        public Nullable<System.DateTime> err_date { get; set; }
    }
}
