//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class legpta_calclog
    {
        public long lpc_id { get; set; }
        public System.DateTime lpc_datelogged { get; set; }
        public Nullable<int> curLeg { get; set; }
        public string ptaType { get; set; }
        public string utilCode { get; set; }
        public Nullable<System.DateTime> newPTA { get; set; }
        public Nullable<System.DateTime> calculatedMax { get; set; }
        public string curTrc { get; set; }
        public Nullable<System.DateTime> today { get; set; }
        public Nullable<byte> approved { get; set; }
        public string approvedBy { get; set; }
        public Nullable<System.DateTime> approvedOn { get; set; }
        public Nullable<bool> Dodataupdate { get; set; }
        public string outStatus { get; set; }
        public Nullable<int> existingLegPTA { get; set; }
        public string messagedesc { get; set; }
        public string instructions { get; set; }
        public Nullable<System.DateTime> pta_hard_max { get; set; }
        public Nullable<System.DateTime> requested_date { get; set; }
        public string requested_user { get; set; }
    }
}
