//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lgh_routesync
    {
        public int lrs_id { get; set; }
        public int lgh_number { get; set; }
        public int mov_number { get; set; }
        public string mpp_id { get; set; }
        public string trc_id { get; set; }
        public string trl_id { get; set; }
        public string lrs_managed { get; set; }
        public decimal lrs_distance { get; set; }
        public int lrs_compliance { get; set; }
        public System.DateTime lrs_date_calculated { get; set; }
        public Nullable<System.DateTime> lrs_date_sent { get; set; }
        public byte[] lrs_message { get; set; }
        public Nullable<int> lrs_response_code { get; set; }
        public string lrs_error_text { get; set; }
        public Nullable<System.DateTime> lrs_error_date { get; set; }
        public string lrs_omnitracs_key { get; set; }
        public Nullable<int> lrs_status { get; set; }
    }
}
