//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lgh_trl_beaming_log
    {
        public int ltb_id { get; set; }
        public int lgh_number { get; set; }
        public int prior_lgh_number { get; set; }
        public string lgh_tractor { get; set; }
        public string lgh_driver1 { get; set; }
        public string lgh_driver2 { get; set; }
        public string lgh_trailer1 { get; set; }
        public string lgh_trailer2 { get; set; }
        public string lgh_cmp_id { get; set; }
        public string prior_cmp_id { get; set; }
        public Nullable<int> lgh_cty_id { get; set; }
        public Nullable<int> prior_cty_id { get; set; }
        public Nullable<int> ord_hdrnumber { get; set; }
        public System.DateTime ltb_date_entered { get; set; }
        public string ltb_user_id { get; set; }
        public string ltb_password { get; set; }
    }
}
