//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class licenselog
    {
        public int lic_logid { get; set; }
        public string lic_userid { get; set; }
        public System.DateTime lic_datetime { get; set; }
        public string lic_msgtype { get; set; }
        public string lic_description { get; set; }
    }
}
