//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LightOrderReasonLog
    {
        public int reason_key { get; set; }
        public int ord_hdrnumber { get; set; }
        public string reason_code { get; set; }
        public string reason_desc { get; set; }
        public string note { get; set; }
        public Nullable<decimal> required_qty { get; set; }
        public Nullable<decimal> ordered_qty { get; set; }
        public string consignee { get; set; }
        public string reason_userstamp { get; set; }
        public System.DateTime reason_timestamp { get; set; }
    }
}
