//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lightdutyschedule
    {
        public int id_num { get; set; }
        public string mpp_id { get; set; }
        public string lds_shift { get; set; }
        public string lds_costcenter { get; set; }
        public Nullable<System.DateTime> lds_date { get; set; }
        public decimal lds_hours { get; set; }
        public string lds_activity { get; set; }
        public string lds_comment { get; set; }
    }
}
