//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadreqdefaultTable
    {
        public string def_id { get; set; }
        public string def_id_type { get; set; }
        public string def_type { get; set; }
        public string def_not { get; set; }
        public string def_manditory { get; set; }
        public Nullable<int> def_quantity { get; set; }
        public byte[] timestamp { get; set; }
        public string def_equip_type { get; set; }
        public string def_cmd_id { get; set; }
        public string def_required { get; set; }
        public Nullable<System.DateTime> def_expire_date { get; set; }
        public string def_cmp_billto { get; set; }
        public int loadreqdefault_ident { get; set; }
        public string def_field { get; set; }
        public string def_units { get; set; }
        public string ltl_applicable { get; set; }
        public Nullable<System.DateTime> def_start_date { get; set; }
        public Nullable<System.DateTime> def_end_date { get; set; }
        public string def_windowday { get; set; }
        public Nullable<int> def_parent_id { get; set; }
    }
}
