//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTLQuote_RequestCommodities
    {
        public long QuoteID { get; set; }
        public string NMFC { get; set; }
        public decimal Weight { get; set; }
        public string WeightUnits { get; set; }
        public decimal Height { get; set; }
        public string HeightUnits { get; set; }
        public decimal Width { get; set; }
        public string WidthUnits { get; set; }
        public decimal Length { get; set; }
        public string LengthUnits { get; set; }
        public decimal Count { get; set; }
        public string CountUnits { get; set; }
        public string Hazardous { get; set; }
        public string Description { get; set; }
    }
}
