//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTLQuote_RequestHeader
    {
        public long QuoteID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<int> QuoteStatus { get; set; }
        public string RootUserName { get; set; }
        public string UserName { get; set; }
        public string contractratesonly { get; set; }
    }
}
