//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m2unfuelpf
    {
        public string ufunit { get; set; }
        public string ufkeyvalue { get; set; }
        public string ufvalue { get; set; }
        public Nullable<System.DateTime> ufstamp { get; set; }
    }
}
