//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class manpowerprofile_snapshots
    {
        public string mpp_id { get; set; }
        public string mpp_tractornumber { get; set; }
        public string mpp_otherid { get; set; }
        public string mpp_firstname { get; set; }
        public string mpp_middlename { get; set; }
        public string mpp_lastname { get; set; }
        public string mpp_address1 { get; set; }
        public string mpp_address2 { get; set; }
        public Nullable<int> mpp_city { get; set; }
        public string mpp_state { get; set; }
        public string mpp_zip { get; set; }
        public Nullable<System.DateTime> mpp_hiredate { get; set; }
        public Nullable<System.DateTime> mpp_senioritydate { get; set; }
        public string mpp_licenseclass { get; set; }
        public string mpp_type1 { get; set; }
        public string mpp_type2 { get; set; }
        public string mpp_type3 { get; set; }
        public string mpp_type4 { get; set; }
        public string mpp_teamleader { get; set; }
        public string mpp_fleet { get; set; }
        public string mpp_terminal { get; set; }
        public string mpp_status { get; set; }
        public Nullable<System.DateTime> mpp_terminationdt { get; set; }
        public string mpp_country { get; set; }
        public Nullable<System.DateTime> SnapshotCreatedDate { get; set; }
    }
}
