//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterBillOutputRestriction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterBillOutputRestriction()
        {
            this.CompanyMasterBillOutputRestrictions = new HashSet<CompanyMasterBillOutputRestriction>();
            this.MasterBills = new HashSet<MasterBill>();
            this.MasterBillOutputRestrictionDetails = new HashSet<MasterBillOutputRestrictionDetail>();
        }
    
        public int MasterBillOutputRestrictionId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string LastUpdateBy { get; set; }
        public int ScheduleId { get; set; }
        public int SystemReportId { get; set; }
        public int ivs_number { get; set; }
        public int CutoffDateTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyMasterBillOutputRestriction> CompanyMasterBillOutputRestrictions { get; set; }
        public virtual DatePropertyType DatePropertyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterBill> MasterBills { get; set; }
        public virtual invoiceselection invoiceselection { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual SystemReport SystemReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterBillOutputRestrictionDetail> MasterBillOutputRestrictionDetails { get; set; }
    }
}
