//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCMACROTEXT
    {
        public string MCT_SERVICE { get; set; }
        public string MCT_DIRECTION { get; set; }
        public short MCT_MACRONUM { get; set; }
        public short MCT_SEQUENCE { get; set; }
        public string MCT_TEMPLATE { get; set; }
    }
}
