//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_position
    {
        public int mp_position { get; set; }
        public Nullable<int> mp_ord { get; set; }
        public Nullable<int> mp_vd { get; set; }
        public Nullable<int> mp_inv { get; set; }
        public Nullable<int> mp_set { get; set; }
        public Nullable<int> mp_adm { get; set; }
        public Nullable<int> mp_fil { get; set; }
        public Nullable<int> mp_tar { get; set; }
        public Nullable<int> mp_psa { get; set; }
        public Nullable<int> mp_aoe { get; set; }
        public Nullable<int> mp_eta { get; set; }
        public Nullable<int> mp_gps { get; set; }
        public Nullable<int> mp_xfc { get; set; }
    }
}
