//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class meterhistory
    {
        public string mh_unittype { get; set; }
        public string mh_unitnumber { get; set; }
        public int mh_reading { get; set; }
        public byte[] mh_units { get; set; }
        public System.DateTime mh_date { get; set; }
        public byte[] timestamp { get; set; }
    }
}
