//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricInProcess
    {
        public Nullable<int> batch { get; set; }
        public int sn { get; set; }
        public Nullable<System.DateTime> ins_dt { get; set; }
        public string note { get; set; }
        public string MetricCode { get; set; }
    }
}
