//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricBranchCasesForQAOnly
    {
        public int sn { get; set; }
        public Nullable<System.DateTime> dt_first { get; set; }
        public Nullable<System.DateTime> dt_last { get; set; }
        public Nullable<int> hits { get; set; }
        public Nullable<int> BranchCase { get; set; }
        public string BranchText { get; set; }
    }
}
