//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricInvalidHistory
    {
        public int sn { get; set; }
        public string BatchGUID { get; set; }
        public Nullable<System.DateTime> dt_insert { get; set; }
        public Nullable<System.DateTime> PlainDate { get; set; }
        public string MetricCode { get; set; }
    }
}
