//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricTempQuarter
    {
        public Nullable<int> spid { get; set; }
        public Nullable<decimal> QuarterlyAve { get; set; }
        public Nullable<int> PlainYear { get; set; }
        public Nullable<int> PlainQuarter { get; set; }
        public int MetricTempQuarter_ident { get; set; }
    }
}
