//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricTemp
    {
        public string ProcName { get; set; }
        public Nullable<decimal> Result { get; set; }
        public Nullable<decimal> ThisCount { get; set; }
        public Nullable<decimal> ThisTotal { get; set; }
        public Nullable<System.DateTime> DateLow { get; set; }
        public Nullable<System.DateTime> DateHigh { get; set; }
        public Nullable<int> UseMetricParms { get; set; }
        public Nullable<int> ShowDetail { get; set; }
        public int SN { get; set; }
    }
}
