//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricUser
    {
        public int sn { get; set; }
        public string NTUser { get; set; }
        public string SQLUser { get; set; }
        public Nullable<int> Disable { get; set; }
        public string GenericUser { get; set; }
        public string GenericPassword { get; set; }
        public string EncryptStyle { get; set; }
    }
}
