//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mobilecommaccount
    {
        public int mba_ident { get; set; }
        public string mba_name { get; set; }
        public string mba_serviceaddress { get; set; }
        public string mba_userid { get; set; }
        public string mba_password { get; set; }
        public string mba_version { get; set; }
        public string mba_isdefault { get; set; }
    }
}
