//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileCommMessageNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MobileCommMessageNode()
        {
            this.MobileCommMessageNode1 = new HashSet<MobileCommMessageNode>();
            this.MobileCommMessageNodeProperties = new HashSet<MobileCommMessageNodeProperty>();
        }
    
        public long NodeContentId { get; set; }
        public long MessageId { get; set; }
        public int NodeDefinitionId { get; set; }
        public Nullable<long> ParentNodeContentId { get; set; }
        public Nullable<long> ChildContentId { get; set; }
    
        public virtual MobileCommMessage MobileCommMessage { get; set; }
        public virtual MobileCommMessage MobileCommMessage1 { get; set; }
        public virtual MobileCommMessageNodeDefinition MobileCommMessageNodeDefinition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileCommMessageNode> MobileCommMessageNode1 { get; set; }
        public virtual MobileCommMessageNode MobileCommMessageNode2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MobileCommMessageNodeProperty> MobileCommMessageNodeProperties { get; set; }
    }
}
