//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MR_GeneralInfoMultiLevel
    {
        public string giml_key { get; set; }
        public string giml_user { get; set; }
        public string giml_report { get; set; }
        public string giml_value { get; set; }
    }
}
