//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MR_ReportingColumns
    {
        public string rc_name { get; set; }
        public string rc_reportname { get; set; }
        public Nullable<int> rc_sequence { get; set; }
        public string rc_summaryoption { get; set; }
        public string rc_username { get; set; }
        public string rc_displayname { get; set; }
        public string rc_datatype { get; set; }
        public bool rc_enablereporttotaling { get; set; }
        public string rc_totalingcalctype { get; set; }
        public Nullable<double> rc_charactermultiplier { get; set; }
        public Nullable<int> rc_lastwidth { get; set; }
        public string rc_sampletext { get; set; }
    }
}
