//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MR_ReportingRestrictions
    {
        public string re_name { get; set; }
        public string re_presname { get; set; }
        public string re_reportname { get; set; }
        public string re_value { get; set; }
        public string re_presvalue { get; set; }
        public string re_datatype { get; set; }
        public string re_operator { get; set; }
        public string re_andor { get; set; }
        public string re_valuetype { get; set; }
        public int re_sequence { get; set; }
        public int re_innersequence { get; set; }
    }
}
