//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class nce_group_membership
    {
        public int ncem_group_id { get; set; }
        public int ncem_email_person_id { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public string created_by { get; set; }
    }
}
