//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class nlmshipment
    {
        public int nlm_shipment_number { get; set; }
        public int accid { get; set; }
        public string acc_name { get; set; }
        public Nullable<System.DateTime> timeout { get; set; }
        public string hazmat { get; set; }
        public string hazmat_code { get; set; }
        public string hazmat_un { get; set; }
        public string hazmat_class { get; set; }
        public string csa_shipment { get; set; }
        public string critical { get; set; }
        public string asap { get; set; }
        public Nullable<System.DateTime> ready { get; set; }
        public string close_time { get; set; }
        public string required_vehicle { get; set; }
        public string terms { get; set; }
        public string mode { get; set; }
        public Nullable<int> miles { get; set; }
        public Nullable<System.DateTime> protect_time { get; set; }
        public Nullable<decimal> tariff_cost { get; set; }
        public string note { get; set; }
        public Nullable<int> total_pieces { get; set; }
        public string shipper_state { get; set; }
        public string shipper_country { get; set; }
        public string consignee_state { get; set; }
        public string consignee_country { get; set; }
        public string fastshipment { get; set; }
        public string ns_first_right_refusal { get; set; }
        public Nullable<decimal> ns_est_fuel_surcharge { get; set; }
    }
}
