//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class nlmshipmentupdate_history
    {
        public int nlm_shipment_number { get; set; }
        public string nlm_url { get; set; }
        public string nlm_retxml { get; set; }
        public string nlm_status { get; set; }
        public System.DateTime archived_time { get; set; }
        public int nlmsuh_id { get; set; }
    }
}
