//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class notesiconrulesmode
    {
        public int nrm_id { get; set; }
        public Nullable<int> nrm_mode_id { get; set; }
        public Nullable<int> nrm_nir_id { get; set; }
        public Nullable<System.DateTime> nrm_created_date { get; set; }
        public string nrm_created_user { get; set; }
    }
}
