//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptLoadStatu
    {
        public int OptLoadStatusID { get; set; }
        public string ConsigneeId { get; set; }
        public string ControlId { get; set; }
        public string Destination { get; set; }
        public string Driver2Id { get; set; }
        public string DriverId { get; set; }
        public Nullable<bool> Hazmat { get; set; }
        public Nullable<bool> HighValue { get; set; }
        public Nullable<decimal> HoursLate { get; set; }
        public Nullable<System.DateTime> LastPingDate { get; set; }
        public string CompanyId { get; set; }
        public Nullable<long> CorrelationId { get; set; }
        public int LoadId { get; set; }
        public string OrderId { get; set; }
        public string Message { get; set; }
        public string NextStopCity { get; set; }
        public string NextStopETA { get; set; }
        public string NextStopState { get; set; }
        public string NextStopZip { get; set; }
        public string Origin { get; set; }
        public string PowerId { get; set; }
        public string PowerDivision { get; set; }
        public string ProxCity { get; set; }
        public string ProxDirection { get; set; }
        public Nullable<decimal> ProxMiles { get; set; }
        public string ProxState { get; set; }
        public string ProxZip { get; set; }
        public string ShipperId { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TotalDelay { get; set; }
        public string TrailerId { get; set; }
    }
}
