//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordertimetable
    {
        public string ord_revtype1 { get; set; }
        public string ord_revtype2 { get; set; }
        public System.DateTime ott_pickuptime { get; set; }
        public System.DateTime ott_minimumtime { get; set; }
        public int ott_speed { get; set; }
    }
}
