//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class osd
    {
        public int osd_stp_number { get; set; }
        public int osd_sequence { get; set; }
        public string osd_type { get; set; }
        public string osd_ref_type { get; set; }
        public string osd_ref_number { get; set; }
        public string osd_description { get; set; }
        public int osd_mov_number { get; set; }
        public Nullable<double> osd_quantity { get; set; }
        public string osd_quantity_unit { get; set; }
        public string osd_responsibility { get; set; }
        public string osd_dest_cmp_id { get; set; }
        public Nullable<int> ord_hdrnumber { get; set; }
        public int osd_id { get; set; }
        public Nullable<System.DateTime> osd_opendate { get; set; }
        public Nullable<System.DateTime> osd_closedate { get; set; }
        public Nullable<decimal> osd_origclaimamount { get; set; }
        public Nullable<decimal> osd_amtpaid { get; set; }
        public Nullable<decimal> osd_amtreceived { get; set; }
    }
}
