//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutOfRouteApproval
    {
        public int oor_id { get; set; }
        public string oor_approved { get; set; }
        public Nullable<int> mov_number { get; set; }
        public int oor_originalMileage { get; set; }
        public int oor_toleranceMiles { get; set; }
        public string oor_toleranceType { get; set; }
        public string oor_toleranceID { get; set; }
        public int oor_acceptedMileage { get; set; }
        public Nullable<int> oor_inroutemiles { get; set; }
        public Nullable<int> oor_triproutemiles { get; set; }
        public string oor_requestby { get; set; }
        public Nullable<System.DateTime> oor_requestdate { get; set; }
        public Nullable<System.DateTime> oor_requestexpdate { get; set; }
        public string oor_decisionby { get; set; }
        public Nullable<System.DateTime> oor_decisiondate { get; set; }
        public string oor_remark { get; set; }
        public Nullable<System.DateTime> oor_applieddate { get; set; }
    }
}
