//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutOfRouteApprovalStop
    {
        public int oor_id { get; set; }
        public int stp_number { get; set; }
        public Nullable<int> stp_mfh_sequence { get; set; }
        public int stp_city { get; set; }
        public bool ooras_is_oor_stp { get; set; }
    }
}
