//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pallet_tracking
    {
        public string pt_tractor_number { get; set; }
        public string pt_trailer_number { get; set; }
        public string pt_carrier_id { get; set; }
        public string pt_company_id { get; set; }
        public decimal pt_pallets_in { get; set; }
        public decimal pt_pallets_out { get; set; }
        public decimal pt_hand_count { get; set; }
        public string pt_pallet_type { get; set; }
        public System.DateTime pt_activity_date { get; set; }
        public int pt_fgt_number { get; set; }
        public int pt_identity { get; set; }
        public string pt_ord_number { get; set; }
        public string pt_comments { get; set; }
        public string pt_entry_type { get; set; }
    }
}
