//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class paperwork_by_assettypes
    {
        public int pat_ident { get; set; }
        public string pat_doctype { get; set; }
        public string asgn_type { get; set; }
        public string asset_type1 { get; set; }
        public string asset_type2 { get; set; }
        public string asset_type3 { get; set; }
        public string asset_type4 { get; set; }
        public string asset_branch { get; set; }
        public string bdt_required_for_fgt_event { get; set; }
    }
}
