//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class partorder_trip
    {
        public int pot_identity { get; set; }
        public Nullable<int> pot_master_ordhdr { get; set; }
        public Nullable<int> pot_ordhdr { get; set; }
    }
}
