//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class partorder_detail
    {
        public int pod_identity { get; set; }
        public int poh_identity { get; set; }
        public string pod_partnumber { get; set; }
        public string pod_description { get; set; }
        public string pod_uom { get; set; }
        public int pod_originalcount { get; set; }
        public Nullable<int> pod_originalcontainers { get; set; }
        public Nullable<int> pod_countpercontainer { get; set; }
        public Nullable<int> pod_adjustedcount { get; set; }
        public Nullable<int> pod_adjustedcontainers { get; set; }
        public Nullable<int> pod_pu_count { get; set; }
        public Nullable<int> pod_pu_containers { get; set; }
        public Nullable<int> pod_del_count { get; set; }
        public Nullable<int> pod_del_containers { get; set; }
        public int pod_cur_count { get; set; }
        public int pod_cur_containers { get; set; }
        public string pod_xdock { get; set; }
        public string pod_release { get; set; }
        public string pod_status { get; set; }
        public string pod_updatedby { get; set; }
        public Nullable<System.DateTime> pod_updatedon { get; set; }
        public Nullable<int> pod_pending_count { get; set; }
        public string pod_sourcefile { get; set; }
        public string pod_skiptrigger { get; set; }
        public Nullable<System.DateTime> pod_pending_date { get; set; }
        public Nullable<double> pod_originalweight { get; set; }
        public Nullable<double> pod_pu_weight { get; set; }
        public Nullable<double> pod_cur_weight { get; set; }
        public Nullable<double> pod_adjustedweight { get; set; }
        public string pod_weightunit { get; set; }
        public string pod_originalUOM { get; set; }
        public Nullable<int> pod_modelyear { get; set; }
        public Nullable<int> pod_forecast1 { get; set; }
        public Nullable<int> pod_forecast2 { get; set; }
        public Nullable<int> pod_forecast3 { get; set; }
    }
}
