//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayDetailTax
    {
        public int Id { get; set; }
        public int origin_pyd_number { get; set; }
        public decimal origin_taxable_amount { get; set; }
        public int payitemtax_id { get; set; }
        public int tar_number { get; set; }
        public decimal tar_rate { get; set; }
        public System.DateTime effective_date { get; set; }
        public string effective_date_source { get; set; }
        public int generated_pyd_number { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string LastUpdateBy { get; set; }
    
        public virtual paydetail paydetail { get; set; }
        public virtual paydetail paydetail1 { get; set; }
        public virtual PayItemTax PayItemTax { get; set; }
    }
}
