//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaySchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaySchedule()
        {
            this.PayScheduleElements = new HashSet<PayScheduleElement>();
            this.PaySchedulePeriods = new HashSet<PaySchedulePeriod>();
            this.PayScheduleRestrictions = new HashSet<PayScheduleRestriction>();
        }
    
        public int PayScheduleId { get; set; }
        public string AccountingType { get; set; }
        public int AssetType { get; set; }
        public bool GlobalSW { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public int UseDateType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Mode { get; set; }
        public Nullable<long> CutOffTimeTicks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayScheduleElement> PayScheduleElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaySchedulePeriod> PaySchedulePeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayScheduleRestriction> PayScheduleRestrictions { get; set; }
    }
}
