//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class payschedulesheader
    {
        public int psh_id { get; set; }
        public string psh_name { get; set; }
        public string psh_description { get; set; }
        public byte[] timestamp { get; set; }
        public string psh_status { get; set; }
    }
}
