//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class paytypeaudit
    {
        public System.DateTime audit_dttm { get; set; }
        public string audit_user { get; set; }
        public string audit_status { get; set; }
        public int pyt_number { get; set; }
        public string pyt_itemcode { get; set; }
        public string pyt_description { get; set; }
        public string pyt_basis { get; set; }
        public string pyt_basisunit { get; set; }
        public Nullable<double> pyt_quantity { get; set; }
        public string pyt_rateunit { get; set; }
        public string pyt_unit { get; set; }
        public Nullable<decimal> pyt_rate { get; set; }
        public string pyt_pretax { get; set; }
        public string pyt_minus { get; set; }
        public string pyt_editflag { get; set; }
        public string pyt_pr_glnum { get; set; }
        public string pyt_ap_glnum { get; set; }
        public string pyt_status { get; set; }
        public Nullable<int> pyt_agedays { get; set; }
        public Nullable<decimal> pyt_fee1 { get; set; }
        public Nullable<decimal> pyt_fee2 { get; set; }
        public string pyt_accept_negatives { get; set; }
        public string pyt_fservprocess { get; set; }
        public string pyt_expchk { get; set; }
        public string pyt_systemcode { get; set; }
        public Nullable<double> pyt_maxrate { get; set; }
        public Nullable<int> pyt_maxenf { get; set; }
        public Nullable<double> pyt_minrate { get; set; }
        public Nullable<int> pyt_minenf { get; set; }
        public Nullable<int> pyt_zeroenf { get; set; }
        public Nullable<int> pyt_incexcoth { get; set; }
        public string pyt_retired { get; set; }
        public string pyt_paying_to { get; set; }
        public Nullable<double> pyt_offset_percent { get; set; }
        public string pyt_offset_for { get; set; }
        public int pyt_editindispatch { get; set; }
        public int paytypeaudit_ident { get; set; }
    }
}
