//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class paytypetax
    {
        public int pyttax_id { get; set; }
        public int pyt_number { get; set; }
        public string pyt_tax1 { get; set; }
        public string pyt_tax2 { get; set; }
        public string pyt_tax3 { get; set; }
        public string pyt_tax4 { get; set; }
        public string pyt_tax5 { get; set; }
        public string pyt_tax6 { get; set; }
        public string pyt_tax7 { get; set; }
        public string pyt_tax8 { get; set; }
        public string pyt_tax9 { get; set; }
        public string pyt_tax10 { get; set; }
        public string tax_triggered_by { get; set; }
    }
}
