//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCATSOutboundQueue
    {
        public int SN { get; set; }
        public Nullable<int> lgh_number { get; set; }
        public Nullable<int> mov_number { get; set; }
        public Nullable<int> ord_hdrnumber { get; set; }
        public Nullable<int> stp_number { get; set; }
        public string poq_deliverto { get; set; }
        public string poq_msgtype { get; set; }
        public string mpp_id { get; set; }
        public System.DateTime poq_shiftdate { get; set; }
        public System.DateTime poq_dateinserted { get; set; }
        public int poq_waitseconds { get; set; }
        public string poq_filterdata { get; set; }
    }
}
