//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permit_Transmit_Log
    {
        public int PTL_ID { get; set; }
        public int P_ID { get; set; }
        public System.DateTime PTL_Transmit_Date { get; set; }
        public string PTL_Transmit_By { get; set; }
        public string PTL_Comment { get; set; }
    
        public virtual Permit Permit { get; set; }
    }
}
