//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permit_Route_Altered
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permit_Route_Altered()
        {
            this.Permit_Route_Detail_Altered = new HashSet<Permit_Route_Detail_Altered>();
        }
    
        public int PRTA_ID { get; set; }
        public int P_ID { get; set; }
        public string PRTA_Name { get; set; }
        public string PRTA_OriginCounty { get; set; }
        public string PRTA_OriginNmstct { get; set; }
        public Nullable<int> PRTA_OriginCity { get; set; }
        public string PRTA_OriginState { get; set; }
        public string PRTA_OriginRoute { get; set; }
        public string PRTA_OriginDirection { get; set; }
        public string PRTA_OriginIntersection { get; set; }
        public Nullable<int> PRTA_OriginMilesBefore { get; set; }
        public string PRTA_DestinationCounty { get; set; }
        public string PRTA_DestinationNmstct { get; set; }
        public Nullable<int> PRTA_DestinationCity { get; set; }
        public string PRTA_DestinationState { get; set; }
        public string PRTA_DestinationRoute { get; set; }
        public string PRTA_DestinationDirection { get; set; }
        public string PRTA_DestinationIntersection { get; set; }
        public Nullable<int> PRTA_DestinationMilesAfter { get; set; }
        public string prta_origincompany { get; set; }
        public string prta_destinationcompany { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permit_Route_Detail_Altered> Permit_Route_Detail_Altered { get; set; }
        public virtual Permit Permit { get; set; }
    }
}
