//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanningBoardType
    {
        public string BoardType { get; set; }
        public string Description { get; set; }
        public string ParentBoardType { get; set; }
        public string IsNestedBoard { get; set; }
        public string ApplicationName { get; set; }
    }
}
