//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class preplan_assets
    {
        public int ppa_id { get; set; }
        public int ppa_lgh_number { get; set; }
        public int ppa_mov_number { get; set; }
        public string ppa_driver1 { get; set; }
        public string ppa_driver2 { get; set; }
        public string ppa_tractor { get; set; }
        public string ppa_trailer1 { get; set; }
        public string ppa_trailer2 { get; set; }
        public string ppa_carrier { get; set; }
        public System.DateTime ppa_createdon { get; set; }
        public string ppa_status { get; set; }
        public string ppa_comment { get; set; }
        public string ppa_chassis { get; set; }
        public string ppa_chassis2 { get; set; }
        public string ppa_dolly { get; set; }
        public string ppa_dolly2 { get; set; }
        public string ppa_trailer3 { get; set; }
        public string ppa_trailer4 { get; set; }
    }
}
