//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_blob_data
    {
        public int blob_id { get; set; }
        public string blob_table { get; set; }
        public string blob_key { get; set; }
        public string blob_desc { get; set; }
        public byte[] blob_data { get; set; }
        public string blob_type { get; set; }
        public string blob_input_method { get; set; }
        public Nullable<short> Blob_nbr { get; set; }
        public string blob_pictype { get; set; }
        public string blob_picdesc { get; set; }
    }
}
