//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_to_gp_paycodes
    {
        public string psgp_PS_paycode { get; set; }
        public string psgp_GP_paycode { get; set; }
        public string psgp_GP_reltype { get; set; }
        public int psgp_identity { get; set; }
    }
}
