//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RailTemplateHeader
    {
        public int rth_id { get; set; }
        public string rth_masterbillid { get; set; }
        public string car_id { get; set; }
        public string rth_origin_ramp { get; set; }
        public string rth_origin_ramp_actual { get; set; }
        public string rth_shipper { get; set; }
        public string rth_dest_ramp { get; set; }
        public string rth_dest_ramp_actual { get; set; }
        public string rth_consignee { get; set; }
        public string rth_billto { get; set; }
        public string rth_terms { get; set; }
        public string rth_notifyparty { get; set; }
        public string rth_notifyfax { get; set; }
        public string rth_notifyphone { get; set; }
        public Nullable<System.DateTime> rth_lastupdate { get; set; }
    }
}
