//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateQuote
    {
        public int ID { get; set; }
        public string BillToID { get; set; }
        public string OriginCompanyID { get; set; }
        public Nullable<int> OriginCityCode { get; set; }
        public string OriginState { get; set; }
        public string OriginPostalCode { get; set; }
        public string OriginCountry { get; set; }
        public string DestinationCompanyID { get; set; }
        public Nullable<int> DestinationCityCode { get; set; }
        public string DestinationState { get; set; }
        public string DestinationPostalCode { get; set; }
        public string DestinationCountry { get; set; }
        public System.DateTime PickupDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreateByUser { get; set; }
    }
}
