//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating_hierarchy_detail
    {
        public int rhd_id { get; set; }
        public int rhh_id { get; set; }
        public int rhd_sequence { get; set; }
        public string rhd_column_name { get; set; }
        public string rhd_column_label { get; set; }
        public string rhd_column_sort_key { get; set; }
        public Nullable<int> rhd_original_sequence { get; set; }
    }
}
