//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class region_hours
    {
        public int region_id { get; set; }
        public byte sunday { get; set; }
        public string sunday_open_shipping1 { get; set; }
        public string sunday_close_shipping1 { get; set; }
        public string sunday_open_receiving1 { get; set; }
        public string sunday_close_receiving1 { get; set; }
        public string sunday_open_shipping2 { get; set; }
        public string sunday_close_shipping2 { get; set; }
        public string sunday_open_receiving2 { get; set; }
        public string sunday_close_receiving2 { get; set; }
        public byte monday { get; set; }
        public string monday_open_shipping1 { get; set; }
        public string monday_close_shipping1 { get; set; }
        public string monday_open_receiving1 { get; set; }
        public string monday_close_receiving1 { get; set; }
        public string monday_open_shipping2 { get; set; }
        public string monday_close_shipping2 { get; set; }
        public string monday_open_receiving2 { get; set; }
        public string monday_close_receiving2 { get; set; }
        public byte tuesday { get; set; }
        public string tuesday_open_shipping1 { get; set; }
        public string tuesday_close_shipping1 { get; set; }
        public string tuesday_open_receiving1 { get; set; }
        public string tuesday_close_receiving1 { get; set; }
        public string tuesday_open_shipping2 { get; set; }
        public string tuesday_close_shipping2 { get; set; }
        public string tuesday_open_receiving2 { get; set; }
        public string tuesday_close_receiving2 { get; set; }
        public byte wednesday { get; set; }
        public string wednesday_open_shipping1 { get; set; }
        public string wednesday_close_shipping1 { get; set; }
        public string wednesday_open_receiving1 { get; set; }
        public string wednesday_close_receiving1 { get; set; }
        public string wednesday_open_shipping2 { get; set; }
        public string wednesday_close_shipping2 { get; set; }
        public string wednesday_open_receiving2 { get; set; }
        public string wednesday_close_receiving2 { get; set; }
        public byte thursday { get; set; }
        public string thursday_open_shipping1 { get; set; }
        public string thursday_close_shipping1 { get; set; }
        public string thursday_open_receiving1 { get; set; }
        public string thursday_close_receiving1 { get; set; }
        public string thursday_open_shipping2 { get; set; }
        public string thursday_close_shipping2 { get; set; }
        public string thursday_open_receiving2 { get; set; }
        public string thursday_close_receiving2 { get; set; }
        public byte friday { get; set; }
        public string friday_open_shipping1 { get; set; }
        public string friday_close_shipping1 { get; set; }
        public string friday_open_receiving1 { get; set; }
        public string friday_close_receiving1 { get; set; }
        public string friday_open_shipping2 { get; set; }
        public string friday_close_shipping2 { get; set; }
        public string friday_open_receiving2 { get; set; }
        public string friday_close_receiving2 { get; set; }
        public byte saturday { get; set; }
        public string saturday_open_shipping1 { get; set; }
        public string saturday_close_shipping1 { get; set; }
        public string saturday_open_receiving1 { get; set; }
        public string saturday_close_receiving1 { get; set; }
        public string saturday_open_shipping2 { get; set; }
        public string saturday_close_shipping2 { get; set; }
        public string saturday_open_receiving2 { get; set; }
        public string saturday_close_receiving2 { get; set; }
    }
}
