//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class req_code
    {
        public int req_number { get; set; }
        public string req_code1 { get; set; }
        public string req_syscode { get; set; }
        public string req_description { get; set; }
        public string req_billable { get; set; }
        public string req_basisunit { get; set; }
        public string req_unit { get; set; }
        public string req_min { get; set; }
        public string req_max { get; set; }
    }
}
