//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResNowPage
    {
        public int sn { get; set; }
        public int MenuSectionSN { get; set; }
        public int Active { get; set; }
        public int Sort { get; set; }
        public int ShowTime { get; set; }
        public string Caption { get; set; }
        public string PageURL { get; set; }
        public string CaptionFull { get; set; }
        public string PagePassword { get; set; }
        public string MetricCode { get; set; }
        public string PageType { get; set; }
        public string CategoryCode { get; set; }
        public Nullable<int> PiePage { get; set; }
        public Nullable<int> TruckMapLat { get; set; }
        public Nullable<int> TruckMapLon { get; set; }
        public Nullable<int> TruckMapFactor { get; set; }
        public string TimeLineTimeFrame { get; set; }
        public Nullable<int> TimeLineUnitsBack { get; set; }
        public string MetricShowcased { get; set; }
        public string DetailMetric { get; set; }
        public string ForcedGraph { get; set; }
        public string MapType { get; set; }
        public Nullable<int> MapWidth { get; set; }
        public Nullable<int> MapHeight { get; set; }
        public string JavaScriptFunctionName { get; set; }
        public string BoundaryFileName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ShowDetail { get; set; }
        public Nullable<int> PrimaryIDColumn { get; set; }
        public Nullable<int> SecondaryIDColumn { get; set; }
        public string PostDataColumns { get; set; }
        public string VariableColumns { get; set; }
        public Nullable<int> ColorNumberColumn { get; set; }
        public string OutputFolder { get; set; }
        public string ServerURL { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> ProcessInterval { get; set; }
        public Nullable<int> MetricCategorySN { get; set; }
        public string SubDirectory { get; set; }
        public Nullable<System.DateTime> DetailDate { get; set; }
        public Nullable<System.DateTime> CurDetailDate { get; set; }
        public string ForcedDetail { get; set; }
        public string DispMode { get; set; }
        public Nullable<int> DetailID { get; set; }
        public string DetailFileName { get; set; }
        public string TimeFrame { get; set; }
        public string selTimeFrame { get; set; }
        public Nullable<int> txtTimeUnitsBack { get; set; }
        public string Chart1 { get; set; }
        public string Chart2 { get; set; }
        public string Chart3 { get; set; }
        public string Chart4 { get; set; }
        public Nullable<int> ReportCardMenuSN { get; set; }
        public string GraphCompare_DateOrderLeftToRight { get; set; }
    }
}
