//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResNowLog
    {
        public int sn { get; set; }
        public System.DateTime dateandtime { get; set; }
        public string source { get; set; }
        public string longdesc { get; set; }
        public string metriccode { get; set; }
    }
}
