//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResNow_TripletsLastRefresh
    {
        public Nullable<System.DateTime> DateLastRefresh { get; set; }
        public byte[] rn_timestamp { get; set; }
        public int ResNow_TripletsLastRefresh_ident { get; set; }
    }
}
