//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResNow_TrailerCache_Final
    {
        public int trailer_key { get; set; }
        public string trailer_id { get; set; }
        public string trailer_number { get; set; }
        public string trailer_type1 { get; set; }
        public string trailer_type2 { get; set; }
        public string trailer_type3 { get; set; }
        public string trailer_type4 { get; set; }
        public string trailer_company { get; set; }
        public string trailer_division { get; set; }
        public string trailer_terminal { get; set; }
        public string trailer_fleet { get; set; }
        public string trailer_branch { get; set; }
        public string trailer_owner { get; set; }
        public string trailer_make { get; set; }
        public string trailer_model { get; set; }
        public int trailer_year { get; set; }
        public Nullable<int> trailer_grossweight { get; set; }
        public Nullable<double> trailer_tareweight { get; set; }
        public short trailer_axles { get; set; }
        public double trailer_height { get; set; }
        public double trailer_length { get; set; }
        public double trailer_width { get; set; }
        public string trailer_licensestate { get; set; }
        public string trailer_licensenumber { get; set; }
        public Nullable<System.DateTime> trailer_startdate { get; set; }
        public Nullable<System.DateTime> trailer_dateacquired { get; set; }
        public Nullable<System.DateTime> trailer_retiredate { get; set; }
        public Nullable<System.DateTime> trailer_DateStart { get; set; }
        public Nullable<System.DateTime> trailer_DateEnd { get; set; }
        public bool trailer_active { get; set; }
        public Nullable<System.DateTime> trailer_Updated { get; set; }
    }
}
