//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResNowIndexesChangedLog
    {
        public int sn { get; set; }
        public Nullable<System.DateTime> dtChange { get; set; }
        public string stage { get; set; }
        public string TableName { get; set; }
        public string index_name { get; set; }
        public string index_description { get; set; }
        public string index_keys { get; set; }
    }
}
