//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class resourcetracking
    {
        public int res_number { get; set; }
        public string res_type { get; set; }
        public string res_id { get; set; }
        public string res_classificationtype { get; set; }
        public string res_classification { get; set; }
        public System.DateTime res_effdatetime { get; set; }
        public string res_editid { get; set; }
        public Nullable<System.DateTime> res_editdatetime { get; set; }
        public string res_createid { get; set; }
        public System.DateTime res_createdatetime { get; set; }
    }
}
