//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMXML_Carrier
    {
        public int id { get; set; }
        public int TmwXmlImportLog_id { get; set; }
        public Nullable<int> RootElementID { get; set; }
        public Nullable<int> ParentLevel { get; set; }
        public Nullable<int> CurrentLevel { get; set; }
        public string CompanyName { get; set; }
        public string RMISCarrierID { get; set; }
        public string TaxID { get; set; }
        public string MCNumber { get; set; }
        public string DOTNumber { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string St { get; set; }
        public string Zip { get; set; }
        public string Contact { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Payto { get; set; }
        public string PaytoAddress { get; set; }
        public string PaytoAddress2 { get; set; }
        public string PaytoCity { get; set; }
        public string PaytoSt { get; set; }
        public string PaytoZip { get; set; }
        public string PaytoCountry { get; set; }
        public string ClientsCarrierID { get; set; }
        public string insdIntraStateNumber { get; set; }
        public string insdIntraStateState { get; set; }
        public string DUNs { get; set; }
        public string Country { get; set; }
        public string Tmw_SynchStatus { get; set; }
        public System.DateTime lastupdatedate { get; set; }
        public string lastupdateuser { get; set; }
        public string PayToEmail { get; set; }
        public string IsFactoring { get; set; }
    }
}
