//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMXML_ClientCarrierAgreement
    {
        public int id { get; set; }
        public int TmwXmlImportLog_id { get; set; }
        public Nullable<int> RootElementID { get; set; }
        public Nullable<int> ParentLevel { get; set; }
        public Nullable<int> CurrentLevel { get; set; }
        public string AgreementTitle { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Contact { get; set; }
        public string Title { get; set; }
        public string Agree { get; set; }
        public Nullable<int> AgreementID { get; set; }
        public Nullable<System.DateTime> OverrideDate { get; set; }
        public string OverrideEditBy { get; set; }
        public string Tmw_SynchStatus { get; set; }
        public System.DateTime lastupdatedate { get; set; }
        public string lastupdateuser { get; set; }
    }
}
