//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RN_OverviewParameter
    {
        public int sn { get; set; }
        public string Side { get; set; }
        public int Sort { get; set; }
        public string Heading { get; set; }
        public string Mode { get; set; }
        public string PrcHeading { get; set; }
        public Nullable<int> NumberOfValues { get; set; }
        public string Colors { get; set; }
        public Nullable<int> DaysBack { get; set; }
        public Nullable<int> DaysRange { get; set; }
        public string Parameters { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> Page { get; set; }
        public string labeldefinition { get; set; }
        public string ProcedureName { get; set; }
        public Nullable<bool> CannedMode { get; set; }
    }
}
