//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class routeheader_audit
    {
        public int audit_id { get; set; }
        public int rth_id { get; set; }
        public string rth_name { get; set; }
        public string audit_user { get; set; }
        public System.DateTime audit_dttm { get; set; }
        public string audit_action { get; set; }
    }
}
