//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class routedetail
    {
        public int rth_id { get; set; }
        public int rtd_id { get; set; }
        public string cmp_id { get; set; }
        public int cty_code { get; set; }
        public string cty_nmstct { get; set; }
        public string rtd_zip { get; set; }
        public int ttr_number { get; set; }
        public Nullable<short> rtd_sequence { get; set; }
    }
}
