//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class safetyStopsList
    {
        public int ssl_Ident { get; set; }
        public int srp_ID { get; set; }
        public string ssl_number { get; set; }
        public string srp_number { get; set; }
        public Nullable<int> stp_number { get; set; }
        public Nullable<int> scl_Ident { get; set; }
        public Nullable<int> fgt_number { get; set; }
        public string cmd_code { get; set; }
        public Nullable<int> mov_number { get; set; }
        public Nullable<int> ord_hdrnumber { get; set; }
        public Nullable<int> lgh_number { get; set; }
    }
}
