//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule_holidays
    {
        public int sch_number { get; set; }
        public int holiday_id { get; set; }
        public short deliver_when { get; set; }
        public string holiday_code { get; set; }
        public string holiday_country { get; set; }
    
        public virtual holiday holiday { get; set; }
    }
}
