//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.DedicatedContracts = new HashSet<DedicatedContract>();
            this.DedicatedRates = new HashSet<DedicatedRate>();
            this.MasterBillOutputRestrictions = new HashSet<MasterBillOutputRestriction>();
            this.PayScheduleElements = new HashSet<PayScheduleElement>();
            this.RecurringAdjustmentInterestSchedules = new HashSet<RecurringAdjustmentInterestSchedule>();
            this.RecurringAdjustmentSchedules = new HashSet<RecurringAdjustmentSchedule>();
            this.ScheduleExceptions = new HashSet<ScheduleException>();
        }
    
        public int ScheduleId { get; set; }
        public int FrequencyType { get; set; }
        public int FrequencyInterval { get; set; }
        public int FrequencyRelativePosition { get; set; }
        public int FrequencyRecurrenceFactor { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DedicatedContract> DedicatedContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DedicatedRate> DedicatedRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterBillOutputRestriction> MasterBillOutputRestrictions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayScheduleElement> PayScheduleElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecurringAdjustmentInterestSchedule> RecurringAdjustmentInterestSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecurringAdjustmentSchedule> RecurringAdjustmentSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleException> ScheduleExceptions { get; set; }
    }
}
