//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class shiftschedules_log
    {
        public int ssl_id { get; set; }
        public int ss_id { get; set; }
        public string ssl_activity { get; set; }
        public Nullable<System.DateTime> ssl_activitydate { get; set; }
        public string ssl_auditreason { get; set; }
        public Nullable<System.DateTime> ssl_createdate { get; set; }
        public string ssl_createdby { get; set; }
        public Nullable<System.DateTime> ssl_lastupdatedate { get; set; }
        public string ssl_lastupdateby { get; set; }
        public string trc_number { get; set; }
        public Nullable<int> ssl_odometer { get; set; }
        public Nullable<bool> ssl_skiptrigger { get; set; }
    }
}
