//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TankForecastDay
    {
        public int ForecastID { get; set; }
        public byte DayNumber { get; set; }
        public decimal PercentOfSales { get; set; }
    
        public virtual TankForecast TankForecast { get; set; }
    }
}
