//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tankdipchart
    {
        public string model_id { get; set; }
        public decimal tank_dip { get; set; }
        public decimal tank_volume { get; set; }
        public int tdc_id { get; set; }
        public Nullable<int> tdc_sequence { get; set; }
    
        public virtual tankmodel tankmodel { get; set; }
    }
}
