//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareLog
    {
        public int SN { get; set; }
        public string tl_RecordType { get; set; }
        public string tl_ord_number { get; set; }
        public Nullable<int> tl_stp_number { get; set; }
        public string tl_shipper { get; set; }
        public string tl_consignee { get; set; }
        public string tl_billto { get; set; }
        public string tl_cmd_code { get; set; }
        public string tl_cmd_class { get; set; }
        public Nullable<decimal> tl_order_qty { get; set; }
        public string tl_order_qty_UOM { get; set; }
        public Nullable<System.DateTime> tl_datetime { get; set; }
        public string tl_trc_number { get; set; }
        public string tl_trl_number { get; set; }
        public string tl_trl_type { get; set; }
        public string tl_mpp_id1 { get; set; }
        public string tl_mpp_id2 { get; set; }
        public Nullable<decimal> tl_fromdriver_gross_wgt { get; set; }
        public string tl_fromdriver_gross_wgt_UOM { get; set; }
        public Nullable<decimal> tl_fromdriver_qty { get; set; }
        public string tl_fromdriver_qtyUOM { get; set; }
        public Nullable<decimal> tl_fromdriver_ConvertedToWeight { get; set; }
        public string tl_fromdriver_ConvertedToWeight_UOM { get; set; }
        public Nullable<int> tl_fuel_gallons { get; set; }
        public Nullable<decimal> tl_fuel_wgt { get; set; }
        public string tl_fuel_wgt_UOM { get; set; }
        public Nullable<decimal> tl_variance { get; set; }
        public Nullable<double> tl_variance_percent { get; set; }
        public Nullable<int> tl_trctrl_gross_wgt { get; set; }
        public Nullable<int> tl_optimum_wgt { get; set; }
        public string tl_optimum_wgt_UOM { get; set; }
        public string tl_country { get; set; }
        public Nullable<int> tl_ResultStatus { get; set; }
    }
}
