//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tariffrowcolumnstl
    {
        public byte[] timestamp { get; set; }
        public int trc_number { get; set; }
        public int tar_number { get; set; }
        public string trc_rowcolumn { get; set; }
        public int trc_sequence { get; set; }
        public string trc_matchvalue { get; set; }
        public Nullable<decimal> trc_rangevalue { get; set; }
        public string trc_multimatch { get; set; }
        public string trc_rateasflat { get; set; }
        public string last_updateby { get; set; }
        public Nullable<System.DateTime> last_updatedate { get; set; }
    }
}
