//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TariffInputSourceArg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TariffInputSourceArg()
        {
            this.ChargeTypeBasisUnitRuleArgs = new HashSet<ChargeTypeBasisUnitRuleArg>();
            this.PayTypeBasisUnitRuleArgs = new HashSet<PayTypeBasisUnitRuleArg>();
        }
    
        public int Id { get; set; }
        public int TariffInputSource_id { get; set; }
        public string InputVariable { get; set; }
        public string InputDataType { get; set; }
        public string MappedVariable { get; set; }
        public string Description { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string LastUpdateBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeTypeBasisUnitRuleArg> ChargeTypeBasisUnitRuleArgs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayTypeBasisUnitRuleArg> PayTypeBasisUnitRuleArgs { get; set; }
        public virtual TariffInputSource TariffInputSource { get; set; }
    }
}
