//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_AUDIT
    {
        public int TASK_AUDIT_ID { get; set; }
        public Nullable<int> TASK_ID { get; set; }
        public Nullable<int> TASK_TEMPLATE_ID { get; set; }
        public string NAME { get; set; }
        public string NAME_P { get; set; }
        public string NAME_F { get; set; }
        public string TASK_LINK_ENTITY_VALUE { get; set; }
        public Nullable<int> TASK_LINK_ENTITY_SYS_VALUE { get; set; }
        public Nullable<int> TASK_LINK_ENTITY_TABLE_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string DESCRIPTION_P { get; set; }
        public string DESCRIPTION_F { get; set; }
        public Nullable<System.DateTime> ORIGINAL_DUE_DATE { get; set; }
        public string ASSIGNED_USER { get; set; }
        public string ASSIGNED_USER_P { get; set; }
        public string ASSIGNED_USER_F { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE_P { get; set; }
        public string DUE_DATE_F { get; set; }
        public Nullable<int> LEAD_TIME { get; set; }
        public Nullable<int> LEAD_TIME_P { get; set; }
        public string LEAD_TIME_F { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public Nullable<int> PRIORITY_P { get; set; }
        public string PRIORITY_F { get; set; }
        public Nullable<System.DateTime> COMPLETED_DATE { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public string ACTIVE_FLAG_P { get; set; }
        public string ACTIVE_FLAG_F { get; set; }
        public string STATUS { get; set; }
        public string STATUS_P { get; set; }
        public string STATUS_F { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_USER { get; set; }
        public string USER_DEFINED_TYPE1 { get; set; }
        public string USER_DEFINED_TYPE1_P { get; set; }
        public string USER_DEFINED_TYPE1_F { get; set; }
        public string USER_DEFINED_TYPE2 { get; set; }
        public string USER_DEFINED_TYPE2_P { get; set; }
        public string USER_DEFINED_TYPE2_F { get; set; }
        public string USER_DEFINED_TYPE3 { get; set; }
        public string USER_DEFINED_TYPE3_P { get; set; }
        public string USER_DEFINED_TYPE3_F { get; set; }
        public string USER_DEFINED_TYPE4 { get; set; }
        public string USER_DEFINED_TYPE4_P { get; set; }
        public string USER_DEFINED_TYPE4_F { get; set; }
        public string PENDING_CHANGES_FLAG { get; set; }
        public string ADDL_INFO1 { get; set; }
        public string ADDL_INFO2 { get; set; }
        public string ADDL_INFO3 { get; set; }
        public string ADDL_INFO4 { get; set; }
        public string ADDL_INFO5 { get; set; }
        public string ADDL_INFO6 { get; set; }
        public string ADDL_INFO7 { get; set; }
        public string ADDL_INFO8 { get; set; }
        public string ADDL_INFO9 { get; set; }
        public string ADDL_INFO10 { get; set; }
        public string ADDL_INFO11 { get; set; }
        public string ADDL_INFO12 { get; set; }
        public string ADDL_INFO13 { get; set; }
        public string ADDL_INFO14 { get; set; }
        public string ADDL_INFO15 { get; set; }
        public string AUDIT_ACTION { get; set; }
        public System.DateTime AUDIT_CREATED_DATE { get; set; }
        public string AUDIT_CREATED_USER { get; set; }
        public string PROMPT_ADD_FLAG { get; set; }
        public string GENERATION_RULE_FLAG { get; set; }
        public string PROMPT_EDIT_FLAG { get; set; }
        public string PROMPT_DELETE_FLAG { get; set; }
        public string PROMPT_HOLD_FLAG { get; set; }
    }
}
