//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_TEMPLATE_QUESTIONS
    {
        public int TTQ_ID { get; set; }
        public string TTQ_QUESTION { get; set; }
        public string TTQ_DEFAULT_ANSWER { get; set; }
        public string TTQ_DEFAULT_ANSWER_ABBR { get; set; }
        public string TTQ_LABELDEFINITION { get; set; }
        public string TTQ_ANSWER_REQUIRED { get; set; }
        public string TTQ_WHEN_TO_PROMPT { get; set; }
        public Nullable<int> TASK_TEMPLATE_ID { get; set; }
        public Nullable<System.DateTime> TTQ_CREATED_DATE { get; set; }
        public string TTQ_CREATED_USER { get; set; }
        public Nullable<System.DateTime> TTQ_MODIFIED_DATE { get; set; }
        public string TTQ_MODIFIED_USER { get; set; }
    }
}
