//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK_TEMPLATE
    {
        public int TASK_TEMPLATE_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string ASSIGNED_USER { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public int LEAD_TIME { get; set; }
        public string ACTIVE_FLAG { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string CREATED_USER { get; set; }
        public System.DateTime MODIFIED_DATE { get; set; }
        public string MODIFIED_USER { get; set; }
        public string USER_DEFINED_TYPE1 { get; set; }
        public string USER_DEFINED_TYPE2 { get; set; }
        public string USER_DEFINED_TYPE3 { get; set; }
        public string USER_DEFINED_TYPE4 { get; set; }
        public string GENERATION_RULE { get; set; }
        public string DATE_RULE { get; set; }
        public string NAME_RULE { get; set; }
        public string TEMPLATE_GROUP_FLAG { get; set; }
        public Nullable<int> PARENT_TASK_TEMPLATE_ID { get; set; }
        public string NAME_F { get; set; }
        public string DESCRIPTION_F { get; set; }
        public string ASSIGNED_USER_F { get; set; }
        public string DUE_DATE_F { get; set; }
        public string LEAD_TIME_F { get; set; }
        public string PRIORITY_F { get; set; }
        public string ACTIVE_FLAG_F { get; set; }
        public string STATUS_F { get; set; }
        public string USER_DEFINED_TYPE1_F { get; set; }
        public string USER_DEFINED_TYPE2_F { get; set; }
        public string USER_DEFINED_TYPE3_F { get; set; }
        public string USER_DEFINED_TYPE4_F { get; set; }
        public string PENDING_CHANGES_FLAG { get; set; }
        public string GENERATION_RULE_FLAG { get; set; }
        public string PROMPT_ADD_FLAG { get; set; }
        public string PROMPT_EDIT_FLAG { get; set; }
        public string PROMPT_DELETE_FLAG { get; set; }
        public string PROMPT_HOLD_FLAG { get; set; }
        public string GENERATION_RULE2 { get; set; }
        public string ASSIGNED_USER_RULE { get; set; }
        public Nullable<int> WORKFLOW_ID { get; set; }
        public string WORKFLOW_TEMPLATE_FLAG { get; set; }
        public string POST_PROCESS { get; set; }
    }
}
