//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblALKRoute
    {
        public int SN { get; set; }
        public string LocationName { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> PointRadius { get; set; }
        public string Distance { get; set; }
        public bool Master { get; set; }
        public string RollingTime { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
