//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCabUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCabUnit()
        {
            this.tblLatLongs = new HashSet<tblLatLong>();
        }
    
        public int SN { get; set; }
        public string UnitID { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Truck { get; set; }
        public Nullable<int> CurrentDispatcher { get; set; }
        public Nullable<int> InBox { get; set; }
        public Nullable<int> OutBox { get; set; }
        public bool Retired { get; set; }
        public Nullable<int> GroupFlag { get; set; }
        public Nullable<int> UpdateGroup { get; set; }
        public string MCPassword { get; set; }
        public Nullable<int> LinkedAddrType { get; set; }
        public Nullable<int> LinkedObjSN { get; set; }
        public string InstanceId { get; set; }
        public bool RouteSyncEnabled { get; set; }
        public bool PositionOnly { get; set; }
        public Nullable<bool> EnableZippedBlobs { get; set; }
        public Nullable<int> OutInstanceId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLatLong> tblLatLongs { get; set; }
        public virtual tblMobileCommType tblMobileCommType { get; set; }
    }
}
