//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCEDriverResponse
    {
        public int SN { get; set; }
        public string tractorID { get; set; }
        public string driverID { get; set; }
        public string unitAddress { get; set; }
        public System.DateTime driverResponseDateTime { get; set; }
        public string driverResponse { get; set; }
        public string updatedBy { get; set; }
        public System.DateTime updatedOn { get; set; }
        public string eventKey { get; set; }
    }
}
