//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFilterElement
    {
        public int flt_SN { get; set; }
        public int fel_SN { get; set; }
        public Nullable<int> fel_Seq { get; set; }
        public string fel_Type { get; set; }
        public string fel_Value { get; set; }
        public int fel_NoView { get; set; }
        public int fel_NoRead { get; set; }
        public int fel_NoSend { get; set; }
        public int fel_PosOnly { get; set; }
        public int fel_noOwner { get; set; }
        public int fel_noContent { get; set; }
    }
}
