//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGeofenceDefault
    {
        public int SN { get; set; }
        public string ID { get; set; }
        public string ID_Type { get; set; }
        public string Event { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Radius { get; set; }
        public string Radius_Units { get; set; }
        public Nullable<int> Latitude_seconds { get; set; }
        public Nullable<int> Longitude_seconds { get; set; }
        public Nullable<int> Begin_Early_Tolerance_min { get; set; }
        public Nullable<int> Begin_Late_Tolerance_min { get; set; }
        public Nullable<int> Arrive_Early_Tolerance_min { get; set; }
        public Nullable<int> Arrive_Late_Tolerance_min { get; set; }
        public Nullable<int> Depart_Early_Tolerance_min { get; set; }
        public Nullable<int> Depart_Late_Tolerance_min { get; set; }
        public Nullable<int> DepartTimeOut { get; set; }
        public string MCVendor { get; set; }
    }
}
