//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGenericReeferUnitType
    {
        public int SN { get; set; }
        public string Name { get; set; }
        public string Mode0 { get; set; }
        public string Mode1 { get; set; }
        public string Mode2 { get; set; }
        public string Mode3 { get; set; }
        public string Mode4 { get; set; }
        public string Mode5 { get; set; }
        public string Mode6 { get; set; }
        public string Mode7 { get; set; }
        public string ExtMode0 { get; set; }
        public string ExtMode1 { get; set; }
        public string ExtMode2 { get; set; }
        public string ExtMode3 { get; set; }
        public string Primary0 { get; set; }
        public string Primary1 { get; set; }
        public string Primary2 { get; set; }
        public string Primary3 { get; set; }
        public string Primary4 { get; set; }
        public string Primary5 { get; set; }
        public string Primary6 { get; set; }
        public string Primary7 { get; set; }
        public string Secondary0 { get; set; }
        public string Secondary1 { get; set; }
        public string Secondary2 { get; set; }
        public string Secondary3 { get; set; }
        public string Secondary4 { get; set; }
        public string Secondary5 { get; set; }
        public string Secondary6 { get; set; }
        public string Secondary7 { get; set; }
        public string Sensor0 { get; set; }
        public string Sensor1 { get; set; }
        public string Setpoint { get; set; }
    }
}
