//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistory_archive
    {
        public int SN { get; set; }
        public Nullable<int> DriverSN { get; set; }
        public Nullable<int> TruckSN { get; set; }
        public Nullable<int> MsgSN { get; set; }
        public bool Chached { get; set; }
    }
}
