//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLink
    {
        public int SN { get; set; }
        public Nullable<int> SourceFormSN { get; set; }
        public Nullable<int> TargetFormSN { get; set; }
        public Nullable<int> MCSN { get; set; }
        public string Status { get; set; }
        public string MCData { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> LinkID { get; set; }
        public Nullable<int> Version { get; set; }
    }
}
