//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQcEssT3020
    {
        public int SN { get; set; }
        public string qcUserIDCompany { get; set; }
        public string equipUnitAddr { get; set; }
        public string equipID { get; set; }
        public string eventKey { get; set; }
        public string eventURL { get; set; }
        public System.DateTime eventTS_GMT { get; set; }
        public System.DateTime sentTS_GMT { get; set; }
        public string equipSCAC { get; set; }
        public string equipType { get; set; }
        public string equipMobileType { get; set; }
        public string equipAlias { get; set; }
        public string equipDeviceID { get; set; }
        public string equipDeviceFirmwareVers { get; set; }
        public string equipVIN { get; set; }
        public string equipDivision { get; set; }
        public string driverID { get; set; }
        public string eventTrigger { get; set; }
        public string triggerData { get; set; }
        public string eventType { get; set; }
        public int speed { get; set; }
        public string parkBrakeStatus { get; set; }
        public float msgLocPosLat { get; set; }
        public float msgLocPosLon { get; set; }
        public System.DateTime msgLocPosTS_GMT { get; set; }
        public float incdntLocPosLat { get; set; }
        public float incdntLocPosLon { get; set; }
        public System.DateTime incdntLocPosTS_GMT { get; set; }
        public int evimsTripDataStartMonth { get; set; }
        public int evimsTripDataStartDay { get; set; }
        public int evimsTripDataStartYear { get; set; }
        public int evimsTripDataStartHour { get; set; }
        public int evimsTripDataStartMinute { get; set; }
        public float evimsTripDataDistance { get; set; }
        public float evimsTripDataMaxSpeed { get; set; }
        public float evimsTripDataFollowPerc0_1 { get; set; }
        public float evimsTripDataFollowPerc1_2 { get; set; }
        public float evimsTripDataCoastingTime { get; set; }
        public int evimsTripDataHB { get; set; }
        public System.DateTime updatedon { get; set; }
        public string updatedby { get; set; }
        public string rawXML { get; set; }
    }
}
