//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaction
    {
        public int SN { get; set; }
        public Nullable<int> FormIn { get; set; }
        public Nullable<int> FormOut { get; set; }
        public string Description { get; set; }
        public bool InCopyToDispatcher { get; set; }
        public bool OutCopyToDispatcher { get; set; }
    }
}
