//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblView
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblView()
        {
            this.tblSelectedViews = new HashSet<tblSelectedView>();
            this.tblViewFields = new HashSet<tblViewField>();
        }
    
        public int SN { get; set; }
        public string ViewName { get; set; }
        public string Description { get; set; }
        public bool OutBoundForm { get; set; }
        public Nullable<int> StoredProcSN { get; set; }
        public bool TriggersReply { get; set; }
        public string ViewCode { get; set; }
        public string DispXactLayer { get; set; }
        public string DispXactViewType { get; set; }
        public string DispXfcTag { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSelectedView> tblSelectedViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblViewField> tblViewFields { get; set; }
    }
}
