//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tchmoneycode
    {
        public string tmc_accountid { get; set; }
        public string tmc_customerid { get; set; }
        public int tmc_sequencenumber { get; set; }
        public string tmc_available { get; set; }
        public string tmc_amountfactor { get; set; }
        public Nullable<decimal> tmc_checkamount { get; set; }
        public string tmc_mcid { get; set; }
        public string tmc_asgntype { get; set; }
        public string tmc_asgnid { get; set; }
        public string tmc_feecode { get; set; }
        public Nullable<System.DateTime> tmc_issuedate { get; set; }
        public string tmc_issuedby { get; set; }
        public string tmc_unitid { get; set; }
        public string tmc_tripnumber { get; set; }
    }
}
