//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tck_fuel_site
    {
        public string tfs_site_number { get; set; }
        public string tfs_site_type { get; set; }
        public string tfs_site_name { get; set; }
        public string tfs_network_flag { get; set; }
        public string tfs_physical_address { get; set; }
        public string tfs_physical_city { get; set; }
        public string tfs_physical_state { get; set; }
        public string tfs_physical_postal_code { get; set; }
        public string tfs_physical_country_code { get; set; }
        public string tfs_phone { get; set; }
        public string tfs_fax { get; set; }
        public string tfs_site_manager { get; set; }
        public string tfs_longitude { get; set; }
        public string tfs_longitude_direction { get; set; }
        public string tfs_latitude { get; set; }
        public string tfs_latitude_direction { get; set; }
        public string tfs_importbatch { get; set; }
        public Nullable<System.DateTime> tfs_updated_on { get; set; }
        public string tfs_updated_by { get; set; }
        public Nullable<System.DateTime> tfs_created_date { get; set; }
    }
}
