//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tck_fuel_optimization
    {
        public int tfo_id { get; set; }
        public Nullable<System.DateTime> tfo_expiration_date { get; set; }
        public Nullable<decimal> tfo_maximum_truck_volume { get; set; }
        public string tfo_status { get; set; }
        public string tfo_sitenumber { get; set; }
        public string tck_account_number { get; set; }
        public string crd_cardnumber { get; set; }
        public string crd_cardnumbershort { get; set; }
        public Nullable<System.DateTime> tfo_updated_on { get; set; }
        public string tfo_updated_by { get; set; }
        public Nullable<System.DateTime> tfo_created_date { get; set; }
    }
}
