//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempordhdr
    {
        public int toh_ordernumber { get; set; }
        public string toh_orderedby { get; set; }
        public string toh_contact { get; set; }
        public string toh_billto { get; set; }
        public System.DateTime toh_shipdate { get; set; }
        public System.DateTime toh_deldate { get; set; }
        public string toh_refnumtype { get; set; }
        public string toh_refnum { get; set; }
        public string toh_shipper { get; set; }
        public string toh_consignee { get; set; }
        public string toh_driver { get; set; }
        public string toh_driver2 { get; set; }
        public string toh_tractor { get; set; }
        public string toh_trailer { get; set; }
        public string toh_rateunit { get; set; }
        public Nullable<decimal> toh_rate { get; set; }
        public Nullable<double> toh_quantity { get; set; }
        public Nullable<decimal> toh_charge { get; set; }
        public string toh_user { get; set; }
        public Nullable<int> toh_tstampq { get; set; }
        public string toh_status { get; set; }
        public Nullable<short> toh_hitemp { get; set; }
        public Nullable<short> toh_lotemp { get; set; }
        public Nullable<short> toh_pallets { get; set; }
        public string toh_comments { get; set; }
        public string toh_error_flag { get; set; }
        public string toh_flag1 { get; set; }
        public string toh_flag2 { get; set; }
        public string toh_flag3 { get; set; }
        public string toh_flag4 { get; set; }
        public Nullable<int> mov_number { get; set; }
        public string toh_edicontrolid { get; set; }
        public Nullable<System.DateTime> toh_bookdate { get; set; }
        public string toh_quantityunit { get; set; }
        public string toh_ordtype { get; set; }
        public string toh_ord_number { get; set; }
        public string toh_ord_terms { get; set; }
        public Nullable<int> toh_ord_totalmiles { get; set; }
        public string toh_inv_status { get; set; }
        public Nullable<int> toh_ord_quantity_type { get; set; }
        public string toh_ord_subcompany { get; set; }
        public string toh_trl_type1 { get; set; }
        public string toh_lgh_type1 { get; set; }
    
        public virtual company company { get; set; }
        public virtual company company1 { get; set; }
        public virtual company company2 { get; set; }
        public virtual company company3 { get; set; }
    }
}
