//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeDetailActivityMapping
    {
        public int ID { get; set; }
        public string BeginningActivityId { get; set; }
        public string EndingActivityId { get; set; }
        public short TimeSourceSystemId { get; set; }
        public string MappedTimeLogActivityLabelAbbr { get; set; }
    
        public virtual TimeSourceSystem TimeSourceSystem { get; set; }
    }
}
