//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timeline_detail_history
    {
        public int tld_hist_identity { get; set; }
        public int tld_group_identity { get; set; }
        public int tld_number { get; set; }
        public int tlh_number { get; set; }
        public Nullable<int> tld_sequence { get; set; }
        public string tld_master_ordnum { get; set; }
        public string tld_route { get; set; }
        public string tld_origin { get; set; }
        public Nullable<System.DateTime> tld_arrive_orig { get; set; }
        public Nullable<int> tld_arrive_orig_lead { get; set; }
        public Nullable<System.DateTime> tld_depart_orig { get; set; }
        public Nullable<int> tld_depart_orig_lead { get; set; }
        public string tld_dest { get; set; }
        public Nullable<System.DateTime> tld_arrive_yard { get; set; }
        public Nullable<int> tld_arrive_lead { get; set; }
        public Nullable<System.DateTime> tld_arrive_dest { get; set; }
        public Nullable<int> tld_arrive_dest_lead { get; set; }
        public string tld_updatedby { get; set; }
        public Nullable<System.DateTime> tld_updatedon { get; set; }
        public string tld_saturday { get; set; }
        public string tld_sunday { get; set; }
    }
}
