//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class timken_orders_hold
    {
        public string bol_number { get; set; }
        public string ord_contact { get; set; }
        public string ord_shipper { get; set; }
        public System.DateTime ord_origin_earliestdate { get; set; }
        public System.DateTime ord_origin_latestdate { get; set; }
        public System.DateTime ord_dest_earliestdate { get; set; }
        public System.DateTime ord_dest_latestdate { get; set; }
        public string ord_consignee { get; set; }
        public string cmd_code { get; set; }
        public int ord_totalpieces { get; set; }
        public string ord_remarks { get; set; }
        public string ord_terms { get; set; }
        public string ord_revtype2 { get; set; }
        public string ord_inv_status { get; set; }
        public string ord_notes { get; set; }
        public int ord_totalweight { get; set; }
        public string yard_number1 { get; set; }
        public string yard_number2 { get; set; }
        public string yard_number3 { get; set; }
        public Nullable<int> ord_hdrnumber { get; set; }
        public string ord_carrier { get; set; }
        public string ord_trailer { get; set; }
        public Nullable<System.DateTime> dispatch_date { get; set; }
        public string ord_status { get; set; }
        public Nullable<int> shipper_invalid { get; set; }
        public Nullable<int> consignee_invalid { get; set; }
        public Nullable<int> cmd_code_invalid { get; set; }
    }
}
