//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM2MCommMappings
    {
        public string MCommSystem { get; set; }
        public string MCommLookupType { get; set; }
        public string MCommLookupValue { get; set; }
        public string tmwLabelDefinition { get; set; }
        public string tmwValue { get; set; }
    }
}
