//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMT_ASSETTRANSFERHISTORY
    {
        public int IDENT { get; set; }
        public Nullable<int> LGH_NUMBER { get; set; }
        public string TRACTOR { get; set; }
        public string DRIVER { get; set; }
        public string TRAILER { get; set; }
        public Nullable<System.DateTime> ASGN_DATE { get; set; }
        public Nullable<System.DateTime> ASGN_ENDDATE { get; set; }
    }
}
