//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMW_GP_AR_payment_information
    {
        public Nullable<int> tmw_gp_ar_pay_id { get; set; }
        public Nullable<int> tmw_gp_ar_invhdrnumber { get; set; }
        public string tmw_gp_ar_docnumber { get; set; }
        public string tmw_gp_ar_custnumber { get; set; }
        public string tmw_gp_ar_applyfromdocnumber { get; set; }
        public System.DateTime tmw_gp_ar_appltoyglpostdate { get; set; }
        public Nullable<decimal> tmw_gp_ar_appliedamount { get; set; }
        public System.DateTime tmw_gp_ar_applydate { get; set; }
        public System.DateTime tmw_gp_ar_applyglfrompostdate { get; set; }
    }
}
