//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmwsuite_workflow_requiredfields
    {
        public int workflow_id { get; set; }
        public string requiredfieldname { get; set; }
        public string requiredfieldvalue { get; set; }
    }
}
