//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMWSystemWideLogging
    {
        public int id { get; set; }
        public string AppID { get; set; }
        public string KeyWord1 { get; set; }
        public string KeyWord2 { get; set; }
        public string Importance { get; set; }
        public string TMWUser { get; set; }
        public string AppVersion { get; set; }
        public string MiscDataDef { get; set; }
        public string MiscData1 { get; set; }
        public string MiscData2 { get; set; }
        public string MiscData3 { get; set; }
        public string MiscData4 { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string Message { get; set; }
    }
}
