//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmwXmlMapperColumnInfo
    {
        public int id { get; set; }
        public int TmwXmlMapperTableInfo_Id { get; set; }
        public string source_columnexpr { get; set; }
        public string target_column { get; set; }
        public System.DateTime lastupdatedate { get; set; }
        public string lastupdateuser { get; set; }
    
        public virtual TmwXmlMapperTableInfo TmwXmlMapperTableInfo { get; set; }
    }
}
