//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPLOrderCostDetailGenActive
    {
        public int mov_number { get; set; }
        public int ord_hdrnumber { get; set; }
        public int lgh_number { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public Nullable<int> Attempts { get; set; }
        public Nullable<System.DateTime> LastAttemptDate { get; set; }
    }
}
