//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tractor_detail
    {
        public string trc_id { get; set; }
        public int trc_det_compartment { get; set; }
        public string trc_det_wet { get; set; }
        public Nullable<double> trc_det_vol { get; set; }
        public string trc_det_uom { get; set; }
        public string trc_det_innage { get; set; }
        public Nullable<double> trc_det_depth { get; set; }
        public string trc_det_ref_pt { get; set; }
        public string trc_det_f_bulk { get; set; }
        public string trc_det_r_bulk { get; set; }
        public string trc_det_chart { get; set; }
        public string trc_det_depth_uom { get; set; }
    }
}
