//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tractor_rtd
    {
        public int rtd_id { get; set; }
        public string rtd_trcid { get; set; }
        public Nullable<System.DateTime> rtd_payperiod { get; set; }
        public string rtd_terminal { get; set; }
        public string rtd_createby { get; set; }
        public Nullable<System.DateTime> rtd_createdt { get; set; }
        public string rtd_lastupdateby { get; set; }
        public Nullable<System.DateTime> rtd_lastupdatedt { get; set; }
        public string rtd_pay_ineligible { get; set; }
    }
}
