//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrailerZoneTemperature
    {
        public int tzt_identity { get; set; }
        public int mov_number { get; set; }
        public int tzt_trailersequence { get; set; }
        public string tzt_zone { get; set; }
        public int tzt_runat { get; set; }
        public Nullable<int> tzt_lastreportedtemp { get; set; }
        public string tzt_type { get; set; }
        public string tzt_updatedby { get; set; }
        public Nullable<System.DateTime> tzt_updated { get; set; }
        public Nullable<int> tzt_runat_high { get; set; }
    }
}
