//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trailer_detail
    {
        public string trl_id { get; set; }
        public int trl_det_compartment { get; set; }
        public string trl_det_wet { get; set; }
        public Nullable<double> trl_det_vol { get; set; }
        public string trl_det_uom { get; set; }
        public string trl_det_innage { get; set; }
        public Nullable<double> trl_det_depth { get; set; }
        public string trl_det_ref_pt { get; set; }
        public string trl_det_f_bulk { get; set; }
        public string trl_det_r_bulk { get; set; }
        public string trl_det_chart { get; set; }
        public string trl_det_depth_uom { get; set; }
        public bool migration_flag { get; set; }
    }
}
