//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class traileralarmresolution
    {
        public int tadr_id { get; set; }
        public string trl_id { get; set; }
        public string acm_system { get; set; }
        public string tadr_alarmtext { get; set; }
        public Nullable<int> tadr_original_tad_id { get; set; }
        public System.DateTime tadr_date { get; set; }
        public string tadr_user { get; set; }
        public string tadr_resolution { get; set; }
        public string tadr_active { get; set; }
    }
}
