//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trailer_unassign_reasonlog
    {
        public int autoreason_id { get; set; }
        public string trl_number { get; set; }
        public string trl_unassigned_precode { get; set; }
        public string trl_unassigned_curcode { get; set; }
        public string trl_unassigned_comments { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string last_updated_by { get; set; }
    }
}
