//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class transf_UserBranches
    {
        public string brn_id { get; set; }
        public int transf_user_id { get; set; }
        public System.DateTime create_dt { get; set; }
        public Nullable<System.DateTime> edit_dt { get; set; }
    }
}
