//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class transcore_settings
    {
        public int tss_identity { get; set; }
        public string tss_account { get; set; }
        public string tss_subaccount { get; set; }
        public string tss_ftpaddress { get; set; }
        public string tss_ftplogin { get; set; }
        public string tss_ftppassword { get; set; }
        public string tss_callbacknumber { get; set; }
        public string tss_dispatcherid { get; set; }
        public Nullable<int> tss_tcpport { get; set; }
        public string tss_default_backhaul { get; set; }
        public string tss_default_comment1 { get; set; }
        public string tss_default_comment2 { get; set; }
    }
}
