//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferConfig
    {
        public int TransferConfigId { get; set; }
        public string Description { get; set; }
        public byte TransferTypeId { get; set; }
        public byte DestinationTypeId { get; set; }
        public string PackageFolder { get; set; }
        public string ProjectName { get; set; }
        public string PackageName { get; set; }
        public string ServerName { get; set; }
        public bool MarkXFR { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public string OutputPath { get; set; }
    
        public virtual TransferDestinationType TransferDestinationType { get; set; }
        public virtual TransferType TransferType { get; set; }
    }
}
