//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class transf_RMColumn
    {
        public int transf_user_id { get; set; }
        public string rmc_rm_name { get; set; }
        public string rmc_col_name { get; set; }
        public int rmc_seq { get; set; }
        public string rmc_header_text { get; set; }
        public System.DateTime create_dt { get; set; }
    }
}
