//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrlStorageInvoiceHistory
    {
        public int TrailerStorageId { get; set; }
        public int ivh_hdrnumber { get; set; }
        public Nullable<System.DateTime> LastBillDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public Nullable<int> FreeDays { get; set; }
    
        public virtual TrlStorage TrlStorage { get; set; }
    }
}
