//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrlStorageContact
    {
        public int TrlStorageContactId { get; set; }
        public int TrlStorageId { get; set; }
        public int TrlStorageContactStatusId { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<System.DateTime> ContactDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual TrlStorage TrlStorage { get; set; }
        public virtual TrlStorageContactStatu TrlStorageContactStatu { get; set; }
    }
}
