//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class truckstop_rebate_breakdown
    {
        public int trb_id { get; set; }
        public string ts_code { get; set; }
        public string trb_value { get; set; }
        public decimal trb_rebate_percentage { get; set; }
        public string trb_min_max_flag { get; set; }
        public string trb_uom_basis { get; set; }
        public decimal trb_rebate_min { get; set; }
        public decimal trb_rebate_max { get; set; }
    
        public virtual truckstop truckstop { get; set; }
    }
}
