//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ttsmenu
    {
        public string app_id { get; set; }
        public int menu_id { get; set; }
        public string menu_name { get; set; }
        public string window_name { get; set; }
        public Nullable<byte> window_size { get; set; }
    }
}
