//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ttsprogram
    {
        public string programid { get; set; }
        public string programname { get; set; }
        public string windowname { get; set; }
        public string helptext { get; set; }
        public byte[] timestamp { get; set; }
        public string rebuildmenulist { get; set; }
    }
}
