//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ttspermission
    {
        public string per_objectname { get; set; }
        public string per_columnname { get; set; }
        public string per_idtype { get; set; }
        public string per_id { get; set; }
        public Nullable<int> per_accesslevel { get; set; }
        public string per_validate { get; set; }
        public string per_errmessage { get; set; }
        public string per_accesslevel_rule { get; set; }
    }
}
