//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ttssecurity
    {
        public string sec_value { get; set; }
        public string sec_idtype { get; set; }
        public string sec_id { get; set; }
        public byte[] timestamp { get; set; }
    }
}
