//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class unitallocation
    {
        public int ualloc_id { get; set; }
        public string unit_number { get; set; }
        public System.DateTime first_effective_date { get; set; }
        public System.DateTime last_effective_date { get; set; }
        public string branch_number { get; set; }
        public string source_system { get; set; }
        public string create_module { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_user { get; set; }
        public string update_module { get; set; }
        public System.DateTime update_date { get; set; }
        public string update_user { get; set; }
    }
}
