//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class userobject_properties
    {
        public int uop_id { get; set; }
        public string uop_user { get; set; }
        public string uop_window { get; set; }
        public string uop_object { get; set; }
        public string uop_property { get; set; }
        public string uop_value { get; set; }
    }
}
