//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_asset_restrictions
    {
        public string usr_userid { get; set; }
        public string uar_asgntype { get; set; }
        public string uar_asgnid { get; set; }
        public string uar_groupflag { get; set; }
        public string uar_description { get; set; }
        public Nullable<System.DateTime> last_updatedate { get; set; }
        public string last_updateby { get; set; }
    }
}
