//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserScreenConfigurationUser
    {
        public string UserID { get; set; }
        public long UserScreenConfigurationID { get; set; }
        public bool IsDefault { get; set; }
        public bool IsGroup { get; set; }
    }
}
