//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class userobject_defaults
    {
        public int uod_id { get; set; }
        public string @object { get; set; }
        public int id { get; set; }
        public string default_type { get; set; }
        public string default_user_id { get; set; }
    }
}
