//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendorpurchaseservice
    {
        public string cmp_id { get; set; }
        public string psd_type { get; set; }
        public Nullable<double> vps_estqty { get; set; }
        public Nullable<decimal> vps_estrate { get; set; }
    }
}
