//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vin_event_export
    {
        public decimal vee_id { get; set; }
        public System.DateTime vee_creation_dt { get; set; }
        public Nullable<System.DateTime> vee_processed_dt { get; set; }
        public string vee_status { get; set; }
        public string vee_error_msg { get; set; }
        public string vee_origin { get; set; }
        public string vee_brand { get; set; }
        public Nullable<int> vee_ord_hdrnumber { get; set; }
        public string vee_vin { get; set; }
        public string vee_event_code { get; set; }
        public string vee_event_name { get; set; }
        public Nullable<System.DateTime> vee_event_date_time { get; set; }
        public string vee_event_data1 { get; set; }
        public string vee_event_data2 { get; set; }
        public string vee_event_data3 { get; set; }
        public string vee_event_data4 { get; set; }
    }
}
