//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vtruck
    {
        public string vtrk_code { get; set; }
        public string vtrk_name { get; set; }
        public Nullable<int> vtrk_weightcap { get; set; }
        public Nullable<int> vtrk_volumecap { get; set; }
        public Nullable<int> vtrk_countcap { get; set; }
        public string vtrk_oneway { get; set; }
    }
}
