//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WatchDogCache
    {
        public int sn { get; set; }
        public string WatchName { get; set; }
        public string Identifier { get; set; }
        public Nullable<System.DateTime> CacheDate { get; set; }
    }
}
