//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class webadmuser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public webadmuser()
        {
            this.webGateChkCompanies = new HashSet<webGateChkCompany>();
            this.webrestricts = new HashSet<webrestrict>();
            this.webscheds = new HashSet<websched>();
            this.webusercompanies = new HashSet<webusercompany>();
            this.webobjects = new HashSet<webobject>();
        }
    
        public string login { get; set; }
        public string name { get; set; }
        public string compid { get; set; }
        public string email { get; set; }
        public string reftype { get; set; }
        public Nullable<short> cmdtyselect { get; set; }
        public Nullable<short> usepscmdtyids { get; set; }
        public Nullable<short> usepscompids { get; set; }
        public string cmdtykey { get; set; }
        public Nullable<short> thirdparty { get; set; }
        public Nullable<short> UseUserDB { get; set; }
        public string UserDBName { get; set; }
        public Nullable<short> quickcompid { get; set; }
        public Nullable<short> createcomp { get; set; }
        public Nullable<short> selallcomp { get; set; }
        public int defaulttemplate { get; set; }
        public short SelListComp { get; set; }
        public string TRSelDfltStat { get; set; }
        public string TRSelSortBy { get; set; }
        public short TRSelShowBillTo { get; set; }
        public short TRDetShowBEO { get; set; }
        public short UOTRDetShowBEO { get; set; }
        public short TRdaterange { get; set; }
        public short CLSShowBEO { get; set; }
        public short UOCLSShowBEO { get; set; }
        public short CLSSortByMove { get; set; }
        public short UOCLSSortByMove { get; set; }
        public short CLSShowTractor { get; set; }
        public short UOCLSShowTractor { get; set; }
        public short CLSShowTrailer { get; set; }
        public short UOCLSShowTrailer { get; set; }
        public short CLSShowRefNumber { get; set; }
        public short UOCLSShowRefNumber { get; set; }
        public short CLSShowMilesLeft { get; set; }
        public short UOCLSShowMilesLeft { get; set; }
        public short CLSShowHoursLeft { get; set; }
        public short UOCLSShowHoursLeft { get; set; }
        public short CLSdaterange { get; set; }
        public short CLSEMail { get; set; }
        public short CSShowLLO { get; set; }
        public short UOCSShowLLO { get; set; }
        public short CSShowEXCO { get; set; }
        public short UOCSShowEXCO { get; set; }
        public short CSdaterange { get; set; }
        public short CSEMail { get; set; }
        public short OSdaterange { get; set; }
        public short OSEMail { get; set; }
        public short OETrlNumFld { get; set; }
        public short OEFlatRateFld { get; set; }
        public short UBO { get; set; }
        public short csrptlevel { get; set; }
        public short CSShowRefNum { get; set; }
        public short UOCSShowRefNum { get; set; }
        public short oefulltmplt { get; set; }
        public short usedefaulttmplt { get; set; }
        public short usedefaultmstr { get; set; }
        public string defaultmaster { get; set; }
        public short tmpltfunc { get; set; }
        public string dfltohreftype { get; set; }
        public short UserSelohreftype { get; set; }
        public string dfltstreftype { get; set; }
        public short UserSelstreftype { get; set; }
        public short TRDetShowEvents { get; set; }
        public short UOTRDetShowEvents { get; set; }
        public short TRDetShowStatus { get; set; }
        public short UOTRDetShowStatus { get; set; }
        public Nullable<short> viewloadreqs { get; set; }
        public Nullable<short> rfq { get; set; }
        public short ordsdirect { get; set; }
        public short stopsalso { get; set; }
        public string language { get; set; }
        public string dateformat { get; set; }
        public short translator { get; set; }
        public short oetrlnum { get; set; }
        public string mapzoomlevel { get; set; }
        public short TRShowPODName { get; set; }
        public short TRStopsOnly { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<webGateChkCompany> webGateChkCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<webrestrict> webrestricts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<websched> webscheds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<webusercompany> webusercompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<webobject> webobjects { get; set; }
    }
}
