//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class webrestrict
    {
        public string login { get; set; }
        public string lbl_def { get; set; }
        public string lbl_abbr { get; set; }
    
        public virtual webadmuser webadmuser { get; set; }
    }
}
