//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class webSessNote
    {
        public string wsn_login { get; set; }
        public int wsn_note_type { get; set; }
        public int wsn_note_seq { get; set; }
        public string wsn_note { get; set; }
    }
}
