//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class webTempCargo
    {
        public int wtc_estatordnumber { get; set; }
        public byte wtc_stpseq { get; set; }
        public Nullable<byte> wtc_cmdseq { get; set; }
        public string wtc_cmdcode { get; set; }
        public string wtc_compid { get; set; }
        public string wtc_stoptype { get; set; }
        public Nullable<byte> wtc_hazardous { get; set; }
    }
}
