//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow_Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workflow_Activity()
        {
            this.Workflow_ActivityRequiredFields = new HashSet<Workflow_ActivityRequiredFields>();
            this.Workflow_ActivityGlobalOptions = new HashSet<Workflow_ActivityGlobalOptions>();
            this.WorkFlow_Sequence = new HashSet<WorkFlow_Sequence>();
        }
    
        public int Activity_ID { get; set; }
        public string Activity_Name { get; set; }
        public string Activity_Type { get; set; }
        public string Activity_RunTimeType { get; set; }
        public string Activity_RunTime { get; set; }
        public string Activity_Workflow_Type { get; set; }
        public string Activity_ClassName { get; set; }
        public string Activity_OutputFieldname { get; set; }
        public string Activity_Active { get; set; }
        public string IsGUI { get; set; }
        public string IsClientSide { get; set; }
    
        public virtual Workflow_Types Workflow_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workflow_ActivityRequiredFields> Workflow_ActivityRequiredFields { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workflow_ActivityGlobalOptions> Workflow_ActivityGlobalOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkFlow_Sequence> WorkFlow_Sequence { get; set; }
    }
}
