//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExtremeMvcApp1_UI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow_QueueData
    {
        public int QueueData_ID { get; set; }
        public string QueueData_ReadStatus { get; set; }
        public int QueueData_WorkflowID { get; set; }
        public Nullable<int> QueueData_AssignedQueue { get; set; }
    
        public virtual Workflow Workflow { get; set; }
        public virtual Workflow_Queues Workflow_Queues { get; set; }
    }
}
